woowacourse-teams/2023-3-ddang

backend/ddang/.gitignore
backend/ddang/build.gradle
backend/ddang/lombok.config
backend/ddang/src/main/java/com/ddang/ddang/LogController.java
backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java
backend/ddang/src/main/java/com/ddang/ddang/log/SlackAppender.java
backend/ddang/src/main/resources/application-local.yml
backend/ddang/src/main/resources/application.yml
backend/ddang/src/main/resources/logback-spring.xml
backend/ddang/src/test/java/com/ddang/ddang/configuration/RestDocsConfiguration.java
backend/ddang/src/test/java/com/ddang/ddang/log/SlackAppenderTest.java

프로젝트 기초 세팅 추가

---

backend/ddang/src/docs/asciidoc/docs.adoc
backend/ddang/src/main/java/com/ddang/ddang/category/application/CategoryService.java
backend/ddang/src/main/java/com/ddang/ddang/category/application/dto/ReadCategoryDto.java
backend/ddang/src/main/java/com/ddang/ddang/category/application/exception/CategoryNotFoundException.java
backend/ddang/src/main/java/com/ddang/ddang/category/presentation/CategoryController.java
backend/ddang/src/main/java/com/ddang/ddang/category/presentation/dto/ReadCategoriesResponse.java
backend/ddang/src/main/java/com/ddang/ddang/category/presentation/dto/ReadCategoryResponse.java
backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java
backend/ddang/src/main/java/com/ddang/ddang/exception/dto/ExceptionResponse.java
backend/ddang/src/main/resources/static/docs/docs.html
backend/ddang/src/test/java/com/ddang/ddang/category/application/CategoryServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/category/presentation/CategoryControllerTest.java

카테고리 api 추가

---

backend/ddang/src/main/java/com/ddang/ddang/category/domain/Category.java
backend/ddang/src/main/java/com/ddang/ddang/region/domain/Region.java
backend/ddang/src/main/java/com/ddang/ddang/region/infrastructure/persistence/JpaRegionRepository.java
backend/ddang/src/test/java/com/ddang/ddang/region/domain/RegionTest.java
backend/ddang/src/test/java/com/ddang/ddang/region/infrastructure/persistence/JpaRegionRepositoryTest.java

지역 엔티티 및 레포지토리 추가

---

backend/ddang/src/main/java/com/ddang/ddang/actuion/domain/Auction.java
backend/ddang/src/main/java/com/ddang/ddang/actuion/domain/Price.java
backend/ddang/src/main/java/com/ddang/ddang/actuion/domain/exception/InvalidPriceValueException.java
backend/ddang/src/main/java/com/ddang/ddang/actuion/infrastructure/persistence/JpaAuctionRepository.java
backend/ddang/src/main/java/com/ddang/ddang/common/entity/BaseTimeEntity.java
backend/ddang/src/main/java/com/ddang/ddang/configuration/JpaConfiguration.java
backend/ddang/src/test/java/com/ddang/ddang/actuion/domain/PriceTest.java
backend/ddang/src/test/java/com/ddang/ddang/actuion/infrastructure/persistence/JpaAuctionRepositoryTest.java

경매 엔티티 및 레포지토리(등록) 추가
closed #26

경매 엔티티 및 레포지토리(등록) 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/CreateAuctionDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
backend/ddang/src/main/java/com/ddang/ddang/auction/domain/BidUnit.java
backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Price.java
backend/ddang/src/main/java/com/ddang/ddang/auction/domain/exception/InvalidPriceValueException.java
backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/JpaAuctionRepository.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/CreateAuctionRequest.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/CreateAuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java
backend/ddang/src/main/java/com/ddang/ddang/exception/dto/ExceptionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/region/application/RegionService.java
backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/domain/BidUnitTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/domain/PriceTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/JpaAuctionRepositoryTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java

경매 api(등록) 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/domain/BidUnit.java
backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Price.java
backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/JpaAuctionRepositoryTest.java

경매 레포지토리(상세 조회) 테스트 추가
close #28

경매 레포지토리(상세 조회) 테스트 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadAuctionDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/application/exception/AuctionNotFoundException.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/AuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/ReadAuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/SellerResponse.java
backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java

경매 api(상세 조회) 추가
현재 ReadAuctionResponse에 카테고리, 이미지, 상태, 지역, 경매 참여자 수, 판매자 정보가 dummy data입니다.
closed #30

경매 api(상세 조회) 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java

경매 도메인 엔티티 삭제 비즈니스 로직 추가
closed #29

경매 도메인 엔티티 삭제 비즈니스 로직 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java

경매 api(삭제) 추가

---

backend/ddang/build.gradle
backend/ddang/src/main/java/com/ddang/ddang/configuration/QuerydslConfiguration.java

queryDsl 설정 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/CreateAuctionDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadAuctionDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/AuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/CategoryResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/CreateAuctionRequest.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/DirectRegionResponse.java

경매 엔티티에 이미지, 카테고리, 지역 필드 임시 추가
- 2차 데모데이에만 사용될 코드입니다.
closed #51

경매 엔티티에 이미지, 카테고리, 지역 필드 임시 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/JpaAuctionRepository.java
backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepository.java
backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/AuctionDetailResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/ReadAuctionDetailResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/ReadAuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/ReadAuctionsResponse.java
backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/JpaAuctionRepositoryTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImplTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/JpaCategoryRepositoryTest.java
backend/ddang/src/test/java/com/ddang/ddang/region/infrastructure/persistence/JpaRegionRepositoryTest.java

경매 api(목록) 추가
- 2차 데모데이에만 사용될 코드가 일부 포함되어 있습니다.
- 추후 리펙터링이 필요합니다. (주석 TODO로 표시)
closed #48

경매 api(목록) 추가

---

.gitmodules

git submodule 적용

---

backend/ddang/src/test/resources/application.yml

테스트 환경 설정 추가

---

android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeViewModel.kt
android/app/src/main/res/layout/fragment_home.xml
android/app/src/main/res/values/strings.xml

경매 상품 목록에서 경매 등록 플로팅 버튼 클릭 시 경매 등록 페이지로 이동하는 기능 구현
크게 없음.
close #63

경매 상품 목록에서 경매 등록 페이지로 이동하는 기능 구현

---

backend/ddang/script/deploy-script.sh

build script 추가

---

backend/ddang/script/deploy-script.sh
backend/ddang/script/dev-pipeline.jenkinsfile

jenkins pipeline script 추가
#35

jenkins pipeline script 추가

---

backend/ddang/src/main/java/com/ddang/ddang/configuration/InitializationAuctionConfiguration.java

경매 더미 데이터 추가

---

android/data/build.gradle
android/data/src/test/java/com/ddangddangddang/data/AuctionRepositoryImplTest.kt
android/data/src/test/java/com/ddangddangddang/data/Fixtures.kt
android/data/src/test/java/com/ddangddangddang/data/MockServer.kt

- MockServer 생성
- Coroutine test 라이브러리를 추가하여 test scope에서 테스트 진행
repository 테스트 시 test scope에서 테스트를 해야 메인 스레드가 죽어서 테스트에 실패하지 않습니다!
closed #83

Repository 테스트 작성 - 경매 상품 목록 조회

---

android/app/src/main/java/com/ddangddangddang/android/feature/common/ViewModelFactory.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionViewModel.kt
android/app/src/main/res/layout/activity_register_auction.xml
android/app/src/main/res/values/strings.xml
android/data/src/main/java/com/ddangddangddang/data/model/request/RegisterAuctionRequest.kt

경매 상품 등록 페이지 서버 연동을 했습니다.
`judgeValidInputs` 함수가 조금 복잡할 수 있습니다.
#82

경매 상품 등록 서버 연동

---

backend/ddang/script/dev-pipeline.jenkinsfile

jenkins slack 연동

---

backend/ddang/build.gradle
backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java

AuctionService 예외 케이스 테스트 추가
closed #57

AuctionService 예외 케이스 테스트 추가

---

android/data/src/test/java/com/ddangddangddang/data/AuctionRepositoryImplTest.kt
android/data/src/test/java/com/ddangddangddang/data/Fixtures.kt
android/data/src/test/java/com/ddangddangddang/data/MockServer.kt

나머지 구현된 Repository 테스트 코드를 작성했습니다.
확인해야하는 코드는 없지만 알아두어야 하는 점
- lastBidPrice의 타입이 우리는 nullable이 아니지만, 서버에서는 nullable를 넘겨주는 경우가 있습니다!! 확인해야합니당
closed #91

Repository 테스트 작성 - 경매 상품 등록, 상세 정보

---

android/app/build.gradle
android/app/src/test/java/com/ddangddangddang/android/Fixtures.kt
android/app/src/test/java/com/ddangddangddang/android/HomeViewModelTest.kt

coroutine test 라이브러리에서 제공하는 coEvery로 repository를 mocking하여 동기적으로 동작하도록 하였습니다.
LiveData를 사용하기 위한 테스트 rule을 추가하였습니다.
ViewModel의 함수 실행에 따라 ViewModel의 데이터가 의도에 맞게 잘 바뀌는지 확인하는 테스트를 진행하였습니다.
크게 없음.
close #92

경매 상품 목록 페이지 ViewModel 테스트 추가

---

.github/workflows/backend_pr_decorator.yml
backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/JpaAuctionRepositoryTest.java

sonarqube와 github actions 설정
closed #75

sonarqube와 github actions 설정

---

.github/workflows/backend_pr_decorator.yml

sonarqube 관련 pr decorator yml 변경
closed #75

sonarqube 관련 pr decorator yml 변경

---

backend/ddang/src/main/java/com/ddang/ddang/configuration/InitializationUserConfiguration.java
backend/ddang/src/main/java/com/ddang/ddang/user/domain/User.java
backend/ddang/src/main/java/com/ddang/ddang/user/infrastructure/persistence/JpaUserRepository.java

사용자 엔티티 생성

---

android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionViewModel.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/remote/ApiResponse.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionCall.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionCallAdapter.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionRetrofit.kt
android/data/src/main/java/com/ddangddangddang/data/remote/CallAdapterFactory.kt
android/data/src/main/java/com/ddangddangddang/data/remote/Service.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt

서버 통신 예외 처리를 위한 CallAdapter 적용
- #124

CallAdapter 적용

---

backend/ddang/src/test/java/com/ddang/ddang/configuration/DatabaseCleanListener.java
backend/ddang/src/test/java/com/ddang/ddang/configuration/IsolateDatabase.java

통합 테스트, 인수 테스트 격리 설정
- `@IsolateDatabase`
- 통합 테스트, 인수 테스트 시 `@SpringBootTest` 어노테이션 대신 붙여줄 수 있는 어노테이션
- `DatabaseCleanListener`
- 데이터베이스 격리를 위해 `TestListener`를 사용한 클래스
[링크](https://github.com/woowacourse-teams/2023-3-ddang/discussions/109) 참고
- closed #108

통합 테스트, 인수 테스트 격리 설정 

---

backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
backend/ddang/src/main/java/com/ddang/ddang/bid/infrastructure/persistence/JpaBidRepository.java
backend/ddang/src/test/java/com/ddang/ddang/bid/infrastructure/persistence/JpaBidRepositoryTest.java

입찰 엔티티 및 레포지토리 추가
주의 깊게 봐야 하는 코드는 아니고 의견을 묻고 싶은 부분이 있습니다.
Bid 엔티티의 createdTime을 BaseTimeEntity를 상속받아 사용하기
이 경우 `cretaedTime`과 `lastModifiedTime`로 클래스를 분리해야 할 듯싶습니다.
- closed #113

입찰 엔티티 및 레포지토리 추가

---

backend/ddang/build.gradle

mysql 의존성 추가

---

backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
backend/ddang/src/main/java/com/ddang/ddang/common/entity/BaseCreateTimeEntity.java
backend/ddang/src/test/java/com/ddang/ddang/bid/infrastructure/persistence/JpaBidRepositoryTest.java

BaseTimeEntity 생성, 수정 시간 분리
- closed #130

BaseTimeEntity 생성, 수정 시간 분리

---

android/app/src/test/java/com/ddangddangddang/android/AuctionDetailVIewModelTest.kt
android/app/src/test/java/com/ddangddangddang/android/Fixtures.kt
android/app/src/test/java/com/ddangddangddang/android/HomeViewModelTest.kt

AuctionDetailViewModelTest 추가
없음
#99

경매 상세 페이지 ViewModel 테스트 추가

---

backend/ddang/build.gradle

flyway mysql 의존성 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
backend/ddang/src/main/java/com/ddang/ddang/chat/domain/Message.java
backend/ddang/src/main/resources/db/migration/V1__init_tables.sql

auction DB 데이터타입 변경

---

backend/ddang/script/dev-deploy-script.sh
backend/ddang/script/dev-pipeline.jenkinsfile
backend/ddang/script/prod-deploy-script.sh
backend/ddang/script/prod-pipeline.jenkinsfile
backend/ddang/src/main/resources/application.yml

운영 서버 빌드 스크립트 작성
- closed #166

운영 서버 빌드 스크립트 작성

---

backend/ddang/script/prod-pipeline.jenkinsfile

prod-pipeline.jenkinsfile 오타 수정

prod-pipeline.jenkinsfile 오타 수정

---

backend/ddang/script/dev-pipeline.jenkinsfile

개발 환경 jenkins pipeline script 수정

개발 환경 jenkins pipeline script 수정

---

backend/ddang/src/main/java/com/ddang/ddang/category/presentation/CategoryController.java
backend/ddang/src/main/java/com/ddang/ddang/region/presentation/RegionController.java
backend/ddang/src/test/java/com/ddang/ddang/category/presentation/CategoryControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/region/presentation/RegionControllerTest.java

카테고리 조회, 직거래 지역 조회 api 수정
없습니다
key : value 타입으로 반환하는 것이 아닌 List 그 자체를 반환해달라는 클라이언트 분들의 요청이 있어서 단순하게 반환 타입만 변경했습니다
- closed #173

카테고리 조회, 직거래 지역 조회 api 수정

---

backend/ddang/src/main/java/com/ddang/ddang/configuration/ImageConfiguration.java

경매 이미지 설정 제거

---

backend/ddang/src/main/java/com/ddang/ddang/configuration/ImageConfiguration.java

이미지 업로드 용량 설정 추가
- 기본 설정이 1MB인거 같아서 급하게 용량 관련 설정을 추가했습니다 
- 구체적인 용량 설정은 추후에 applicaiton.yml같은걸로 외부로 빼야할 것 같아요

이미지 업로드 용량 설정 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/CreateAuctionDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionDetailResponse.java
backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImplTest.java

경매 엔티티에 카테고리 엔티티, 직거래 지역 엔티티 연관관계 세팅 방식 변경
- 연관관계 편의 메서드를 삭제하고 생성자를 통해 초기화하도록 했습니다
- 모두 다 같이 정한 내용이라 가볍게 보고 넘어가주시면 될 것 같습니다 
- closed #191

경매 엔티티에 카테고리 엔티티, 직거래 지역 엔티티 연관관계 세팅 방식 변경

---

android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionViewModel.kt

기존 이미지 파일을 압축하여 캐시에 저장 후 서버로 전송하는 기능 구현
먼저 기존 이미지 파일의 Uri를 bitmap으로 변환합니다.
기존 이미지 파일의 bitmap의 가로와 세로를 각각 1/2 크기로 줄인 후 JPEG 파일로 변환합니다. 이때 이미지의 품질은 원본 이미지의 90%로 설정하였습니다.
이렇게 가공된 파일을 캐시 디렉토리에 저장합니다.
이때 가공된 파일에는 기존 이미지 파일의 방향 정보가 포함되지 않게 됩니다. 그래서 기존 이미지 파일의 방향 정보를 가져와서 가공된 파일에 설정해주었습니다.
최종적으로 가공된 파일을 서버로 전송하게 됩니다.
- closed: #193

이미지를 압축하여 캐시에 저장하는 기능 구현

---

backend/ddang/src/docs/asciidoc/docs.adoc
backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java
backend/ddang/src/main/java/com/ddang/ddang/image/application/exception/InvalidImagePathException.java
backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/LocalStoreImageProcessor.java
backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/exception/StoreImageException.java
backend/ddang/src/main/java/com/ddang/ddang/image/infrastructure/local/exception/StoreImageFailureException.java
backend/ddang/src/main/resources/static/docs/docs.html
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/configuration/RestDocsConfiguration.java
backend/ddang/src/test/java/com/ddang/ddang/image/infrastructure/local/LocalStoreImageProcessorTest.java
backend/ddang/src/test/java/com/ddang/ddang/image/presentation/ImageControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/region/presentation/RegionControllerTest.java

경매 관련 예외 핸들링, 테스트 케이스, 문서 추가
- GlobalExceptionHandler
- UserNotFoundException이 2개(bid, chat 패키지)가 있기 때문에 두 가지 예외에 대해 모두 핸들러를 등록했습니다
- RestDocsConfiguration
- deprecated 된 메서드가 있어 수정했습니다
- closed #189

예외 핸들링, 테스트 케이스, 문서 추가

---

backend/ddang/src/main/resources/db/migration/V4__alter_auction_tables.sql

flyway로 인해 기존 데이터의 입찰자 수가 null이 되는 문제 해결

flyway로 인해 기존 데이터의 입찰자 수가 null이 되는 문제 해결

---

backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
backend/ddang/src/main/java/com/ddang/ddang/bid/domain/Bid.java
backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
backend/ddang/src/test/java/com/ddang/ddang/bid/application/BidServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/bid/domain/BidTest.java

두 가지 예외 통합

---

android/app/src/main/java/com/ddangddangddang/android/feature/detail/bid/SubmitBidFailureResponse.kt

경매 입찰 실패 시 응답 메시지 수정

---

backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/AuctionDetailResponse.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java

상세 정보에서는 입찰자 수가 0으로 전달되는 문제 해결
상세 dto는 수정을 하지 않다니..!
이런 엄청난 실수를... 😱
번거롭게 해드려 죄송합니다 🙇‍♀️🙇‍♀️🙇‍♀️
- closed #208

상세 정보에서는 입찰자 수가 0으로 전달되는 문제 해결

---

backend/ddang/src/docs/asciidoc/docs.adoc
backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/BidController.java
backend/ddang/src/main/resources/static/docs/docs.html
backend/ddang/src/test/java/com/ddang/ddang/bid/application/BidServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/bid/presentation/BidControllerTest.java

입찰 관련 테스트 추가 및 api 문서
- 예외 발생 테스트 추가
- 입찰 등록 api 문서화
- 입찰 조회 api 문서화
- closed #158

입찰 관련 테스트 추가 및 api 문서

---

backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/ReadAuctionDto.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/ReadParticipatingChatRoomDto.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/exception/UserNotAccessibleException.java
backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/response/ReadAuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/response/ReadChatRoomResponse.java
backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java
backend/ddang/src/test/java/com/ddang/ddang/chat/application/ChatRoomServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/domain/ChatRoomTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java

채팅방 상세 정보 조회 api 추가
채팅방 목록 조회랑 거의 비슷해서 가볍게 봐주시면 될 것 같아요!
- closed #145

채팅방 상세 정보 조회 api 추가

---

backend/ddang/src/main/resources/db/migration/V5__alter_user_tables.sql

flyway version 6 script 오타 수정
죄송합니다 스크립트에 오타를 내버렸습니다...그리고 몰랐습니다...죄송합니다..

flyway version 5 script 오타 수정

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/ddangddangddang/android/feature/common/ViewModelFactory.kt
android/app/src/main/java/com/ddangddangddang/android/feature/login/LoginActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/login/LoginViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/splash/SplashActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/splash/SplashViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/global/DdangDdangDdang.kt
android/app/src/main/res/layout/activity_login.xml
android/app/src/main/res/layout/activity_splash.xml
android/app/src/main/res/values/strings.xml
android/app/src/main/res/values/themes.xml
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/AuthRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/CategoryRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/RegionRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/model/request/RefreshTokenRequest.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionRetrofit.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionService.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuthRetrofit.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuthService.kt
android/data/src/main/java/com/ddangddangddang/data/remote/Service.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepositoryImpl.kt
android/data/src/main/java/com/ddangddangddang/data/repository/CategoryRepositoryImpl.kt
android/data/src/main/java/com/ddangddangddang/data/repository/RegionRepositoryImpl.kt

자동 로그인 기능 구현
없음
- Resolved:  #246

자동 로그인 기능 구현

---

backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationService.java
backend/ddang/src/main/java/com/ddang/ddang/authentication/infrastructure/jwt/JwtDecoder.java
backend/ddang/src/main/java/com/ddang/ddang/authentication/presentation/AuthenticationController.java
backend/ddang/src/main/java/com/ddang/ddang/authentication/presentation/dto/response/ValidatedTokenResponse.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java

토큰 유효성 검증 api 구현
- AuthenticationService.validateToken()이 마침 [제이미가 이전에 남겨주셨던 리뷰](https://github.com/woowacourse-teams/2023-3-ddang/pull/231#discussion_r1287908051)와 잘 맞는 것 같아서 가져왔습니다
- Interceptor에서는 Optional.empty()가 나오면 예외 상황이지만 유효성 검증시에는 Optional.empty()면 false를 반환해주는 식이라고 봐주시면 될 것 같습니다
- 코드 자체는 매우 간단해서 한 번 쓱 봐주시면 될 것 같습니다
- closed #252

토큰 유효성 검증 api 추가

---

backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/response/CreateChatRoomResponse.java

채팅방 생성 시 채팅방 아이디 바디로 넘기도록 수정

---

android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageViewModel.kt
android/app/src/main/res/layout/fragment_my_page.xml
android/app/src/main/res/values/strings.xml

개인정보처리방침 버튼을 누르면 노션 링크로 이동합니다.
없음.
- Closed: #285

개인정보처리방침 추가

---

android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageRoomActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageRoomViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/model/mapper/AuctionDetailModelMapper.kt
android/app/src/main/java/com/ddangddangddang/android/model/mapper/MessageRoomDetailModelMapper.kt
android/app/src/main/java/com/ddangddangddang/android/model/mapper/MessageRoomModelMapper.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/model/response/ChatLastMessageResponse.kt
android/data/src/main/java/com/ddangddangddang/data/model/response/ChatPartnerResponse.kt
android/data/src/main/java/com/ddangddangddang/data/model/response/ChatRoomPreviewResponse.kt
android/data/src/main/java/com/ddangddangddang/data/model/response/SellerResponse.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionService.kt

신고하기 및 쪽지방 정보 Dto 서버랑 안맞는 버그 수정
없음
- #286

신고하기 및 쪽지방 정보 Dto 서버랑 안맞는 버그 수정

---

backend/ddang/src/main/resources/db/migration/V9__alter_user_tables.sql

flyway script version 9 수정 

---

backend/ddang/src/docs/asciidoc/docs.adoc
backend/ddang/src/main/resources/static/docs/docs.html
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java

경매 api 문서 최신화, 인증 & 인가 api 문서화
- 문서화를 위한 테스트 코드 추가와 문서화 쪽 코드밖에 수정사항이 없어서 딱히 없습니다 
- closed #280

경매 api 문서 최신화, 인증 & 인가 api 문서화

---

backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionDetailResponse.java
backend/ddang/src/main/resources/static/docs/docs.html
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java

- 경매 상세 조회 api 응답 필드 추가
- AuctionController.read()의 ReadAuctionDetailResponse 생성 시 userInfo를 전달하고 seller.id와 userInfo.id를 비교하는 로직만 추가했습니다.
- - isOwner: boolean 형식으로 반환합니다.
- closed #298

경매 상세 조회 api 응답 필드 추가

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageAdapter.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageRoomActivity.kt
android/app/src/main/res/layout/activity_message_room.xml

마지막 메시지 위치로 리사이클러뷰 위치 이동되는 기능 추가
DiffUtil로 비동기적으로 비교 연산을 한 다음 수행될 콜백을 등록했습니다.
- #304

마지막 메시지 위치로 리사이클러뷰 위치 이동되는 기능 추가

---

backend/ddang/src/docs/asciidoc/docs.adoc
backend/ddang/src/main/resources/static/docs/docs.html
backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java

채팅 api 문서화

---

android/app/build.gradle
android/data/build.gradle

안드로이드 버전 수정

---

android/app/src/main/java/com/ddangddangddang/android/feature/splash/SplashViewModel.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepositoryImpl.kt

자동 로그인 버그 수정
- 뷰모델에서 액세스 토큰을 검증하는 레포지토리 메소드를 실행하고,(만약 실패면, 리프레시를 하고 다시 액세스 토큰을 검증했음) 이게 응답 자체는 Success이지만, 우리가 받은 응답 바디 안의 불리언 값을 확인 안해주고 있던 버그 수정
- AuthRepository 의 verifyToken 안에서 조건문 버그 수정
없음
- #356

자동 로그인 버그 수정

---

backend/ddang/src/main/java/com/ddang/ddang/configuration/fcm/FcmConfiguration.java

fcm private key를 찾을 수 없는 문제 해결

fcm private key를 찾을 수 없는 문제 해결

---

backend/ddang/src/main/resources/db/migration/V11__create_profile_image_tables.sql

V11 flyway script 수정

---

backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslChatRoomAndMessageRepositoryImpl.java

채팅방 목록 조회 시 groupBy 문제 해결

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/ddangddangddang/android/feature/common/ViewModelFactory.kt
android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/participateAuction/ParticipateAuctionActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/participateAuction/ParticipateAuctionViewModel.kt
android/app/src/main/res/layout/activity_participate_auction.xml
android/app/src/main/res/values/strings.xml
android/data/src/main/java/com/ddangddangddang/data/datasource/UserRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionService.kt
android/data/src/main/java/com/ddangddangddang/data/repository/UserRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/UserRepositoryImpl.kt

참여 경매 목록을 볼 수 있는 기능을 추가했습니다.
없음
- close: #397

참여 경매 목록 기능

---

backend/ddang/src/main/java/com/ddang/ddang/authentication/presentation/AuthenticationController.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java

탈퇴 시 요청 메서드 변경
`delete` -> `post`

탈퇴 시 요청 메서드 변경

---

android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageViewModel.kt
android/app/src/main/res/layout/fragment_my_page.xml
android/app/src/main/res/values/strings.xml
android/data/src/main/java/com/ddangddangddang/data/datasource/AuthRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/model/request/WithdrawalRequest.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionService.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuthService.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepositoryImpl.kt

회원 탈퇴 기능 서버 연동했습니다!
없음.
- Closes #403

회원 탈퇴 기능 서버 연동

---

android/app/src/main/java/com/ddangddangddang/android/feature/profile/ProfileChangeActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/profile/ProfileChangeViewModel.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/UserRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionService.kt
android/data/src/main/java/com/ddangddangddang/data/repository/UserRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/UserRepositoryImpl.kt

회원 정보 수정 api 변경에 따른 수정
fileBody를 널로 보낼 수 있게 하도록 수정했습니다.
- #406 close

회원 정보 수정 api 변경에 따른 수정

---

backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationService.java
backend/ddang/src/main/java/com/ddang/ddang/authentication/configuration/KakaoProvidersConfigurationProperties.java
backend/ddang/src/main/java/com/ddang/ddang/authentication/infrastructure/oauth2/OAuth2UserInformationProvider.java
backend/ddang/src/main/java/com/ddang/ddang/authentication/infrastructure/oauth2/kakao/KakaoUserInformationProvider.java
backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
backend/ddang/src/main/java/com/ddang/ddang/bid/infrastructure/persistence/JpaBidRepository.java
backend/ddang/src/main/resources/application-local.yml
backend/ddang/src/main/resources/static/docs/docs.html
backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/oauth2/kakao/KakaoUserInformationProviderTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/bid/infrastructure/persistence/JpaBidRepositoryTest.java

탈퇴 시 권한이 없다고 뜨는 문제 해결
제가 카카오 access token과 땅땅땅 access token 사이에서 혼란이 있어 문제가 발생했었네요...
압도적 죄송... 🙇‍♀️
approve 다 해주시면 submodule에 카카오 admin key 올려두도록 하겠습니다.
- closed #417

탈퇴 시 권한이 없다고 뜨는 문제 해결

---

backend/ddang/src/main/java/com/ddang/ddang/authentication/infrastructure/oauth2/kakao/KakaoUserInformationProvider.java

카카오 요청 관련 문제 해결

---

android/app/src/main/res/color/black_900_to_red_100_checked.xml
android/app/src/main/res/layout/activity_main.xml
android/app/src/main/res/values/colors.xml
android/app/src/main/res/values/themes.xml

바텀네비게이션바 디자인 수정

---

backend/ddang/src/main/resources/db/migration/V14__alter_chat_room_report_tables.sql

쪽지 신고 fk관련 flyway 수정

---

android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageRoomActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageRoomViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/report/ReportActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/report/ReportViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/model/ReportType.kt
android/app/src/main/res/values/strings.xml
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/model/request/ReportAuctionArticleRequest.kt
android/data/src/main/java/com/ddangddangddang/data/model/request/ReportMessageRoomRequest.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionService.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt

쪽지방 신고 기능 추가
ReportActivity진입시, ReportType을 줘야 하도록 getIntent를 수정했습니다.
- close: #430

쪽지방 신고 기능 추가

---

backend/ddang/src/main/java/com/ddang/ddang/device/application/DeviceTokenService.java
backend/ddang/src/main/java/com/ddang/ddang/device/domain/DeviceToken.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java

디바이스 토큰 cascade 설정 삭제

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
backend/ddang/src/main/java/com/ddang/ddang/region/infrastructure/persistence/JpaRegionRepository.java
backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/region/infrastructure/persistence/JpaRegionRepositoryTest.java

경매 등록 로직 변경
- 경매 등록 로직 변경
- JpaRegionRepository에서 세 번째 id를 in절로 한 번에 조회하는 기능을 만들었습니다
- 경매 조회 로직 컨벤션(Repository에서 조회하는 행위를 메서드로 분리하지 않는 것)을 지키도록 리펙토링했습니다
- closed #442

경매 등록 로직 변경

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadAuctionDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadAuctionsDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
backend/ddang/src/main/java/com/ddang/ddang/auction/domain/AuctionStatus.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/AuctionDetailResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/CreateAuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/response/AuctionDetailResponse.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/response/ReadAuctionResponse.java
backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/user/presentation/UserAuctionControllerTest.java

경매 엔티티에 경매 상태를 계산하는 기능 추가
- 드디어 enum으로 교체했습니다 그래서 딱히 없고 그냥...좀 광범위하게 바뀌기는 했습니다 
- Auction 도메인 엔티티에서 직접 LocalDateTime.now()를 호출하지 않고 외부에서 주입받도록 했습니다
- closed #139

경매 엔티티에 경매 상태를 계산하는 기능 추가

---

backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java

알림 메시지만 수정한거라 별거 없습니다.
트랜잭션 분리 (어제 메리가 쪽지 부분 처리해서 pr 작성하신거)를 이 pr에서 할지, 메리 pr에서 할지, 이슈 새로 팔지 고민이네요.
- closed #452

입찰 알림의 바디 메시지 수정

---

backend/ddang/src/main/java/com/ddang/ddang/notification/application/FcmNotificationService.java

절전모드에서도 알림을 받을 수 있도록 수정
- closed #457

절전모드에서도 알림을 받을 수 있도록 수정

---

backend/ddang/src/main/java/com/ddang/ddang/authentication/infrastructure/jwt/JwtEncoder.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/application/BlackListTokenServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/jwt/JwtDecoderTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/jwt/JwtEncoderTest.java

Token 발급 시 어떤 Type인지 반환값에서 명시
- `JwtEncoder`에서 `Bearer `을 붙여서 반환하도록 변경했습니다 그래서 별거 없습니다 
- closed #459

Token 발급 시 어떤 Type인지 반환값에서 명시

---

android/app/src/main/java/com/ddangddangddang/android/feature/main/MainActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageViewModel.kt
android/app/src/main/res/layout/fragment_my_page.xml
android/app/src/main/res/values/strings.xml

마이페이지에서 알림 설정 기능 카테고리를 클릭하면 알림 설정창으로 이동합니다.
없음.
- close: #449

마이페이지에서 알림 설정창으로 이동하는 기능 추가

---

backend/ddang/src/main/java/com/ddang/ddang/notification/application/util/NotificationProperty.java

알림 타입과 관련된 key 값 변경

---

backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslChatRoomAndMessageAndImageRepositoryImpl.java

채팅방에 메시지가 없을 때 목록 조회 시 예외 발생하지 않도록 수정

채팅방에 메시지가 없을 때 목록 조회 시 예외 발생하지 않도록 수정

---

backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/AuctionDetailResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/CreateAuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/SellerResponse.java
backend/ddang/src/main/java/com/ddang/ddang/authentication/infrastructure/oauth2/Oauth2Type.java
backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/BidController.java
backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/dto/response/ReadBidResponse.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/response/ReadAuctionInChatRoomResponse.java
backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/response/ReadChatPartnerResponse.java
backend/ddang/src/main/java/com/ddang/ddang/image/domain/AuctionImage.java
backend/ddang/src/main/java/com/ddang/ddang/image/presentation/ImageController.java
backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageRelativeUrl.java
backend/ddang/src/main/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculator.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/UserAuctionController.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/ReadUserResponse.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/response/AuctionDetailResponse.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/response/ReadAuctionDetailResponse.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/response/ReadAuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/response/ReadAuctionsResponse.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/response/ReadUserResponse.java
backend/ddang/src/test/java/com/ddang/ddang/image/presentation/ProfileImageControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/image/presentation/util/ImageUrlCalculatorTest.java
backend/ddang/src/test/java/com/ddang/ddang/user/infrastructure/persistence/JpaUserRepositoryTest.java

이미지 url 관련 네이밍 수정
- 네이밍 관련해 수정을 진행하며 추가적으로 진행한 내용은 아래와 같습니다.
해당 부분에 대해서도 확인해주시면 감사하겠습니다.
1. ImageUrlCaclulator의 비슷한 메서드 통합
2. UserAuctionController에서 Util을 사용하도록 수정
todo에 고민 하나 있으니 확인 부탁드려요.
- clsoed #469

이미지 url 관련 네이밍 수정

---

backend/ddang/src/test/java/com/ddang/ddang/notification/application/FcmNotificationServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/notification/application/fixture/FcmNotificationServiceFixture.java

알림 관련 테스트 코드 리팩토링
- 간단한 분리 작업이었어서 딱히 없는 것 같습니다.
- closed #481

알림 관련 테스트 코드 리팩토링

---

.github/workflows/backend_pr_decorator.yml

슬랙 메세지 링크 정상화
딱히 없습니다 
- closed #510

슬랙 메세지 링크 정상화

---

backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/application/fixture/AuctionServiceFixture.java

- AuctionService가 ChatRoomService를 의존하고 있던 시절의 테스트가 그대로 남아있더군요. 제가 싼 💩입니다.. 옛날옛적에 프로덕션 코드만 리팩토링 하고 테스트에서 제거를 안했네요.. 그대로 남아있으면 혼란만 생길 것 같아 제거했습니다.
- closed #539

경매 서비스 테스트에서 불필요한 레거시 테스트 제거

---

backend/ddang/src/main/java/com/ddang/ddang/category/presentation/CategoryController.java
backend/ddang/src/main/java/com/ddang/ddang/configuration/CacheConfiguration.java
backend/ddang/src/main/java/com/ddang/ddang/region/presentation/RegionController.java

카테고리와 직거래 지역 조회 api 호출시 메모리 캐시 적용
- 어려운 코드는 없습니다
- 간단 용어 정리나 해당 코드로 얻을 수 있는 장점, 실제 단축된 시간은 [디스커션](https://github.com/woowacourse-teams/2023-3-ddang/discussions/543)을 참고해주세요 
- closed #534

카테고리와 직거래 지역 조회 api 호출시 메모리 캐시 적용

---

backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/ReadChatRoomWithLastMessageDto.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/ReadParticipatingChatRoomDto.java
backend/ddang/src/main/java/com/ddang/ddang/chat/domain/ChatRoom.java
backend/ddang/src/main/java/com/ddang/ddang/report/application/ChatRoomReportService.java
backend/ddang/src/main/java/com/ddang/ddang/report/application/dto/ReadChatRoomInReportDto.java
backend/ddang/src/main/java/com/ddang/ddang/report/application/dto/ReadChatRoomReportDto.java
backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/application/fixture/ChatRoomServiceFixture.java
backend/ddang/src/test/java/com/ddang/ddang/chat/application/fixture/MessageServiceFixture.java
backend/ddang/src/test/java/com/ddang/ddang/chat/domain/ChatRoomTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/domain/fixture/ChatRoomFixture.java
backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/fixture/ChatRoomControllerFixture.java
backend/ddang/src/test/java/com/ddang/ddang/report/presentation/fixture/ReportControllerFixture.java

채팅 가능 기간 관련 정책 제거 및 탈퇴한 사용자와 채팅이 불가능하도록 기능 추가
- closed #537

채팅 가능 기간 관련 정책 제거 및 탈퇴한 사용자와 채팅이 불가능하도록 기능 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadReviewDetailResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/SellerResponse.java
backend/ddang/src/main/java/com/ddang/ddang/review/application/dto/CreateReviewDto.java
backend/ddang/src/main/java/com/ddang/ddang/review/presentation/dto/request/CreateReviewRequest.java
backend/ddang/src/main/java/com/ddang/ddang/review/presentation/dto/response/ReadReviewDetailResponse.java
backend/ddang/src/main/java/com/ddang/ddang/review/presentation/dto/response/ReadReviewResponse.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/ReadUserResponse.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/response/ReadAuctionDetailResponse.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/response/ReadUserResponse.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/response/SellerResponse.java
backend/ddang/src/test/java/com/ddang/ddang/review/presentation/fixture/ReviewControllerFixture.java

응답의 소수 데이터를 Float 타입으로 변경
- 변환하고자 하는 값이 Double이었던 것는 null 체크 후 Float으로 변경했고,
- 변환하고자 하는 값이 double 이었던 것은 null 체크 없이 Float.valueOf(String.valueOf(~))로 했습니다.
- closed #554

응답의 소수 데이터를 Float 타입으로 변경

---

backend/ddang/src/main/java/com/ddang/ddang/configuration/metric/LogicMetricAop.java
backend/ddang/src/main/java/com/ddang/ddang/configuration/metric/MetricConfiguration.java

비즈니스 로직 호출 메트릭 추가
- 코드 상 어려운 부분은 없습니다
- 자세한 내용은 [디스커션](https://github.com/woowacourse-teams/2023-3-ddang/discussions/547)을 참고해주세요
- closed #546

비즈니스 로직 호출 메트릭 추가

---

backend/ddang/script/dev-pipeline.jenkinsfile
backend/ddang/script/prod-pipeline.jenkinsfile

젠킨스 스크립트 수정

---

android/app/src/main/res/layout/activity_auction_detail.xml
android/app/src/main/res/layout/fragment_home.xml
android/app/src/main/res/layout/view_profile.xml
android/app/src/main/res/values/strings.xml

신뢰도 관련 뷰 활성화하고 신뢰도 평가 이전인 경우에는 ( - ) 로 표시하도록 처리했습니다.
없음.
- close: #561

신뢰도 관련 뷰 활성화 및 신뢰도 평가 이전 표시 추가

---

android/app/src/main/java/com/ddangddangddang/android/feature/common/ErrorTypeHandler.kt
android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/message/MessageFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/message/MessageViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/review/UserReviewDialog.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/review/UserReviewViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/myAuction/MyAuctionActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/myAuction/MyAuctionViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/participateAuction/ParticipateAuctionActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/participateAuction/ParticipateAuctionViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/category/SelectCategoryActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/category/SelectCategoryViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/region/SelectRegionsActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/region/SelectRegionsViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/report/ReportActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/report/ReportViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/search/SearchFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/search/SearchViewModel.kt
android/app/src/main/res/layout/activity_message_room.xml
android/app/src/main/res/layout/activity_select_regions.xml
android/app/src/main/res/values/strings.xml
android/data/src/main/java/com/ddangddangddang/data/datasource/UserRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionService.kt
android/data/src/main/java/com/ddangddangddang/data/repository/UserRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/UserRepositoryImpl.kt

빠져있던 에러처리로직을 전부 추가했습니다.
아래처럼, 확장함수로 분리했습니다.
- close: #560

에러 처리 로직 추가

---

android/app/build.gradle
android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageViewModel.kt
android/app/src/main/res/layout/fragment_my_page.xml
android/app/src/main/res/values/strings.xml

문의하기 클릭 시 땅땅땅에 이메일을 보낼 수 있게 화면을 띄워줍니다.
이메일을 보낼 수 있는 앱만 띄울 수 있게 intent를 정의했습니다!
- close: #568

feat: 문의하기 기능 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/dto/AuctionAndImageQueryProjectionDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/dto/ChatRoomAndImageQueryProjectionDto.java
backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/dto/ChatRoomAndMessageAndImageQueryProjectionDto.java
backend/ddang/src/main/java/com/ddang/ddang/image/domain/AuctionImage.java
backend/ddang/src/main/java/com/ddang/ddang/notification/application/util/NotificationProperty.java
backend/ddang/src/test/java/com/ddang/ddang/bid/presentation/BidControllerTest.java

불필요한 todo 삭제

---

backend/ddang/script/prod-deploy-script.sh

운영 서버 배포 스크립트에 무중단 배포 적용
없음
- closed #619

운영 서버 배포 스크립트에 무중단 배포 적용

---

android/app/build.gradle
android/app/src/main/res/layout/item_detail_image.xml
android/settings.gradle

PhotoView 라이브러리를 추가해서 적용했습니다.
https://github.com/Baseflow/PhotoView
위의 라이브러리를 사용했습니다. 글라이드 사용이 되더라고요. 기본적으로는 AppCompatImageView를 상속 구현하도록 되어있네요.
- close: #622

이미지 상세 페이지 확대 기능 추가

---

backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java

메시지 전송 시 작성자 이미지가 전송되도록 수정

---

backend/ddang/script/prod-deploy-script.sh
backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadChatRoomDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/dto/AuctionAndImageQueryProjectionDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/dto/ChatRoomAndImageQueryProjectionDto.java
backend/ddang/src/main/java/com/ddang/ddang/chat/infrastructure/persistence/dto/ChatRoomAndMessageAndImageQueryProjectionDto.java
backend/ddang/src/main/java/com/ddang/ddang/image/domain/AuctionImage.java
backend/ddang/src/main/java/com/ddang/ddang/notification/application/NotificationEventListener.java
backend/ddang/src/main/java/com/ddang/ddang/notification/application/util/NotificationProperty.java
backend/ddang/src/main/java/com/ddang/ddang/user/domain/User.java
backend/ddang/src/test/java/com/ddang/ddang/bid/presentation/BidControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/application/ChatRoomServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/application/fixture/ChatRoomServiceFixture.java

백엔드 브랜치 develop 브랜치에 최신화

---

backend/ddang/src/main/java/com/ddang/ddang/auction/configuration/validator/ClosingTimeLimit.java
backend/ddang/src/main/java/com/ddang/ddang/auction/configuration/validator/ClosingTimeValidator.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/request/CreateAuctionRequest.java

- 경매 등록 시 경매 마감 시간 제한 변경
- 현재 일자로부터 최대 30일 지정 가능 
- closed #613

경매 등록 시 경매 마감 시간 제한 변경

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
backend/ddang/src/main/java/com/ddang/ddang/category/application/CategoryService.java
backend/ddang/src/main/java/com/ddang/ddang/category/domain/repository/CategoryRepository.java
backend/ddang/src/main/java/com/ddang/ddang/category/infrastructure/persistence/CategoryRepositoryImpl.java
backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/CategoryRepositoryImplTest.java
backend/ddang/src/test/java/com/ddang/ddang/category/infrastructure/persistence/fixture/CategoryRepositoryFixture.java

Category 관련 인프라 리펙토링
- closed #648

Category 관련 인프라 리펙토링

---

backend/ddang/src/main/java/com/ddang/ddang/authentication/application/BlackListTokenService.java
backend/ddang/src/main/java/com/ddang/ddang/authentication/domain/repository/BlackListTokenRepository.java
backend/ddang/src/main/java/com/ddang/ddang/authentication/infrastructure/persistence/BlackListTokenRepositoryImpl.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/BlackListTokenServiceFixture.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/domain/BlackListTokenTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/BlackListTokenRepositoryImplTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/JpaBlackListTokenRepositoryTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/fixture/BlackListTokenRepositoryFixture.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/infrastructure/persistence/fixture/JpaBlackListTokenRepositoryFixture.java

- Authentication 관련 인프라 리펙토링
- JpaBlackListToken에서 누락된 테스트 추가 
- closed #645

Authentication 관련 인프라 리펙토링

---

backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/BidController.java
backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/dto/response/ReadBidsResponse.java
backend/ddang/src/main/resources/static/docs/docs.html
backend/ddang/src/test/java/com/ddang/ddang/bid/presentation/BidControllerTest.java

입찰 목록 조회 API 명세 변경에 따른 수정
크게 수정된 부분은 없습니다!
List를 감싸던 dto만 제거했습니다.
- closed #659

입찰 목록 조회 API 명세 변경에 따른 수정

---

backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionQnaController.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadQuestionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadUserInAuctionQuestionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/qna/application/QuestionService.java
backend/ddang/src/main/java/com/ddang/ddang/qna/application/dto/ReadQnaDto.java
backend/ddang/src/main/java/com/ddang/ddang/qna/application/dto/ReadQnasDto.java
backend/ddang/src/main/java/com/ddang/ddang/qna/application/dto/ReadQuestionDto.java
backend/ddang/src/main/java/com/ddang/ddang/qna/presentation/QnaController.java
backend/ddang/src/main/java/com/ddang/ddang/report/presentation/dto/response/ReadReporterResponse.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionQnaControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/fixture/AuctionQuestionControllerFixture.java
backend/ddang/src/test/java/com/ddang/ddang/qna/application/QuestionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/qna/application/fixture/QuestionServiceFixture.java
backend/ddang/src/test/java/com/ddang/ddang/report/application/QuestionReportServiceTest.java

Q&A 목록 조회 API 명세 변경에 따른 수정
- Question response dto에 isQuestioner이라는 boolean 값 추가
- 조회한 사용자가 질문 작성자인지 확인을 위한 값
- api 명세와 다른 부분 수정
- closed #660

Q&A 목록 조회 API 명세 변경에 따른 수정

---

backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationService.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/application/fixture/AuthenticationServiceFixture.java

- 신규 회원가입이 안되는 버그 수정
- 빌더 패턴에서 초기화하지 않던 필드 추가 
- 테스트 케이스 검증 추가 
- 잘못된 테스트 케이스 수정
엔초 감사합니다 
- closed #680

신규 회원가입이 안되는 버그 수정

---

backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
backend/ddang/src/main/java/com/ddang/ddang/bid/domain/repository/BidRepository.java
backend/ddang/src/main/java/com/ddang/ddang/bid/infrastructure/persistence/BidRepositoryImpl.java
backend/ddang/src/main/java/com/ddang/ddang/bid/infrastructure/persistence/JpaBidRepository.java
backend/ddang/src/test/java/com/ddang/ddang/auction/application/fixture/AuctionServiceFixture.java
backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/fixture/AuctionRepositoryImplFixture.java
backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/fixture/QuerydslAuctionRepositoryForListFixture.java
backend/ddang/src/test/java/com/ddang/ddang/bid/application/fixture/BidServiceFixture.java
backend/ddang/src/test/java/com/ddang/ddang/bid/infrastructure/persistence/BidRepositoryImplTest.java
backend/ddang/src/test/java/com/ddang/ddang/bid/infrastructure/persistence/JpaBidRepositoryTest.java
backend/ddang/src/test/java/com/ddang/ddang/bid/infrastructure/persistence/fixture/BidRepositoryImplFixture.java
backend/ddang/src/test/java/com/ddang/ddang/chat/application/fixture/ChatRoomServiceFixture.java
backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/fixture/ChatRoomAndImageRepositoryImplFixture.java
backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/fixture/ChatRoomAndMessageAndImageRepositoryImplFixture.java
backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/fixture/ChatRoomRepositoryImplFixture.java
backend/ddang/src/test/java/com/ddang/ddang/notification/application/fixture/FcmNotificationServiceFixture.java
backend/ddang/src/test/java/com/ddang/ddang/notification/application/fixture/NotificationEventListenerFixture.java

Bid 관련 인프라 리팩토링
딱히 없습니다!
- closed #671

Bid 관련 인프라 리팩토링

---

backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java
backend/ddang/src/main/java/com/ddang/ddang/user/application/UserService.java
backend/ddang/src/main/java/com/ddang/ddang/user/application/exception/AlreadyExistsNameException.java
backend/ddang/src/main/java/com/ddang/ddang/user/domain/repository/UserRepository.java
backend/ddang/src/main/java/com/ddang/ddang/user/infrastructure/persistence/JpaUserRepository.java
backend/ddang/src/main/java/com/ddang/ddang/user/infrastructure/persistence/UserRepositoryImpl.java
backend/ddang/src/test/java/com/ddang/ddang/user/application/UserServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/user/application/fixture/UserServiceFixture.java
backend/ddang/src/test/java/com/ddang/ddang/user/infrastructure/persistence/JpaUserRepositoryTest.java
backend/ddang/src/test/java/com/ddang/ddang/user/infrastructure/persistence/UserRepositoryImplTest.java
backend/ddang/src/test/java/com/ddang/ddang/user/infrastructure/persistence/fixture/JpaUserRepositoryFixture.java
backend/ddang/src/test/java/com/ddang/ddang/user/infrastructure/persistence/fixture/UserRepositoryImplFixture.java
backend/ddang/src/test/java/com/ddang/ddang/user/presentation/UserControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/user/presentation/fixture/UserControllerFixture.java

닉네임 수정 시 중복 예외 처리 추가
- closed #687

닉네임 수정 시 중복 예외 처리 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadAuctionDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadAuctionDetailResponse.java
backend/ddang/src/main/resources/static/docs/docs.html
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/fixture/AuctionControllerFixture.java
backend/ddang/src/test/java/com/ddang/ddang/user/presentation/fixture/UserAuctionControllerFixture.java

경매 상세 조회 시 로그인한 사용자가 해당 경매의 최고 입찰자인지 여부를 반환하도록 응답 형식 변경
없는 것 같습니다 
- closed #692

경매 상세 조회 시 로그인한 사용자가 해당 경매의 최고 입찰자인지 여부를 반환하도록 응답 형식 변경

---

backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadQnaResponse.java
backend/ddang/src/main/java/com/ddang/ddang/qna/application/dto/ReadAnswerDto.java
backend/ddang/src/main/java/com/ddang/ddang/qna/application/dto/ReadQuestionDto.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/fixture/AuctionQuestionControllerFixture.java
backend/ddang/src/test/java/com/ddang/ddang/qna/application/fixture/QuestionServiceFixture.java
backend/ddang/src/test/java/com/ddang/ddang/qna/infrastructure/JpaQuestionRepositoryTest.java
backend/ddang/src/test/java/com/ddang/ddang/qna/infrastructure/fixture/JpaQuestionRepositoryFixture.java

질문과 답변 조회 시 삭제된 답변은 보이지 않도록 수정
- closed #697

질문과 답변 조회 시 삭제된 답변은 보이지 않도록 수정

---

backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/response/ReadQnaResponse.java

답변이 null인 경우 처리가 안 되는 문제 해결

---

backend/ddang/src/main/resources/db/migration/V20__alter_answer_tables.sql

flyway 스크립트 문제 해결
