woowacourse-teams/2023-3-ddang

android/app/src/main/java/com/ddangddangddang/android/feature/home/AuctionAdapter.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/AuctionViewHolder.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/model/AuctionHomeStatusModel.kt
android/app/src/main/res/layout/item_home_auction.xml
android/app/src/main/res/layout/view_auction_image_cover_with_status.xml

경매 상품 목록에서 특정 경매 상품 선택 시 경매 상세 페이지로 이동한다.
ViewModel의 event를 observe해서 이벤트를 발생시키는 부분을 처음 짜봐서 확인 부탁드려요~!
Adapter에 ViewModel의 함수를 생성자 주입하고 경매 상품이 선택되었을 때 ViewModel의 함수가 호출되고 이를 observe해서 Fragment에 정의된 경매 상세 페이지 이동 함수를 호출하도록 했어요!
ViewModel의 데이터가 이벤트 발생에 필요하지 않지만 ViewModel을 거친 이유는 뷰에서 발생하는 모든 유저 이벤트를 ViewModel에서 처리하고 observe하도록 통일하기 위함입니다!
또한 지금 당장은 ViewModel의 데이터가 필요하지 않지만 추후에 필요하게 되었을 때 뷰 계층의 코드 수정이 최대한 없게 하기 위함도 있어요! 
close #59

경매 상품 선택 시 경매 상세를 보여주는 기능 구현

---

android/app/src/main/java/com/ddangddangddang/android/feature/common/ViewModelFactory.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/model/mapper/AuctionHomeModelMapper.kt
android/app/src/test/java/com/ddangddangddang/android/HomeViewModelTest.kt
android/app/src/test/java/com/ddangddangddang/android/LiveDataExtension.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionLocalDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt
android/data/src/test/java/com/ddangddangddang/data/AuctionRepositoryImplTest.kt

경매 데이터 캐싱 전략을 적용하여 새로운 경매글을 등록했을 때 경매 목록이 자동으로 갱신되도록 함.
- #117

경매 데이터 캐싱 전략 적용

---

backend/ddang/src/main/java/com/ddang/ddang/configuration/InitializationRegionConfiguration.java
backend/ddang/src/main/java/com/ddang/ddang/configuration/RestTemplateConfiguration.java
backend/ddang/src/main/java/com/ddang/ddang/region/application/RegionService.java
backend/ddang/src/main/java/com/ddang/ddang/region/domain/InitializationRegionProcessor.java
backend/ddang/src/main/java/com/ddang/ddang/region/infrastructure/api/RestTemplateInitRegionProcessor.java
backend/ddang/src/main/java/com/ddang/ddang/region/infrastructure/api/dto/ApiAccessTokenResponse.java
backend/ddang/src/main/java/com/ddang/ddang/region/infrastructure/api/dto/ResultApiRegionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/region/infrastructure/api/dto/TotalApiRegionResponse.java
backend/ddang/src/main/java/com/ddang/ddang/region/infrastructure/api/exception/RegionApiException.java
backend/ddang/src/main/resources/application-local.yml
backend/ddang/src/test/java/com/ddang/ddang/configuration/DatabaseCleanListener.java
backend/ddang/src/test/java/com/ddang/ddang/region/application/RegionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/region/infrastructure/api/RestTemplateInitRegionProcessorTest.java
backend/ddang/src/test/resources/application.yml

지역 초기 데이터 저장
- InitializationRegionProcessor & RestTemplateInitRegionProcessor
- 특정 기술 스택과 API(RestTemplate, 단계별 주소 조회 API)에 종속적이지 않도록 추상화
- InitializationRegionConfiguration
- ApplicationRunner로 애플리케이션 초기화 시 실행되도록 하기 위함
- 운영 서버에서까지 사용해야 하지만, DB 상황에 따라 사용 유무가 갈리므로 @ConditionalOnProperty를 통해 외부 설정을 통한 분기처리
- RegionService
- 다른 초기 데이터 설정과는 달리 운영 서버에서도 사용될 것이기 때문에 트랜잭션을 직접 InitializationRegionConfiguration에서 관리하지 않고 RegionService에서 트랜잭션을 관리하도록 함
- 추후 CQRS를 도입한다면 지역 읽기와 지역 초기화로 분리할 수도? 있을듯 
- RestTemplateInitRegionProcessorTest
- 어노테이션이랑 Mock 서버를 활용한 테스트
[링크](https://github.com/woowacourse-teams/2023-3-ddang/discussions/114) 참고
---
현재 애플리케이션 실행 시 실행되지 않고 예외가 발생하는데, 그 이유는 `application-local.yml`에 `open.api.region`의 `service`와 `secret`이 필요하기 때문입니다.
이 정보는 민감한 부분이라 여기서는 대충 더미 데이터를 넣었고, 이후 서브모듈에서 …

지역 초기 데이터 저장

---

android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionViewModel.kt

DatePicker에서 선택한 날짜의 달이 잘못된 값으로 보이는 버그
DatePicker의 month는 `0~11`,
LocalDateTime의 month는 `1~12` 범위라서 이 차이를 계산해주어야했습니다.
closed #101

경매 상품 등록 페이지 DatePicker month -1 버그

---

android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeViewModel.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/remote/Service.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt

경매 목록 무한 스크롤 구현
리사이클러뷰 스크롤 리스너 로직 확인 부탁드려요~!
현재 로직은 화면에 보여진 마지막 아이템의 포지션이 전체 경매 아이템 수보다 5개 이하로 적으면 새로운 경매 아이템을 불러오고 있습니다!
- #126

경매 목록 무한 스크롤 구현

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/ddangddangddang/android/feature/common/BindingAdapter.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionImageAdapter.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionImageViewHolder.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/model/RegisterImageModel.kt
android/app/src/main/java/com/ddangddangddang/android/util/view/SnackbarFactory.kt
android/app/src/main/res/layout/activity_register_auction.xml
android/app/src/main/res/layout/item_register_image.xml
android/app/src/main/res/values/strings.xml
android/app/src/test/java/com/ddangddangddang/android/HomeViewModelTest.kt

경매 등록 시 갤러리에서 사진을 선택하고 보여주는 기능 구현
API 30 이상에서 지원해주는 Photo Picker를 사용했습니다.
하위 버전에서도 동작할 수 있도록 service도 추가해주었습니다!
같은 사진이어도 중복으로 올라갈 수 있도록 하였고 업로드 시 시간을 id로 가지도록 했습니다!
- close : #142

경매 등록 시 갤러리에서 사진 선택하는 기능 구현

---

android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionViewModel.kt
android/app/src/main/res/layout/activity_register_auction.xml
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt

갤러리에서 가져온 이미지 Uri를 File로 변환 후 서버에 전송 가능한 MultipartBody로 변환하는 작업을 진행했습니다.
Uri를 File로 변환하고 이후에 DataSource에서 File을 MultipartBody로 변환하는 부분을 확인해주시면 좋을 것 같습니다!
Uri로부터 절대 경로를 가져오는 로직도 확인 부탁드려요!
버전 분기처리를 하지 않았는데도 API 28과 API 33에서 잘 동작하여 일단은 버전 분기처리를 하지 않았습니다!
- closed : #159

이미지 Uri를 MultipartBody로 변환

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/CreateAuctionDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/request/CreateAuctionRequest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java

경매 등록 api 변경
- AuctionController.create()
- `@ModelAttribute`에서 `@RequestParam`으로 변경했습니다.
- 둘 다 `@RequestParam`이지만 사실상 `@RequestParam CreateAuctionRequest request`은 application/json 타입으로 처리됩니다.
- AuctionControllerTest.경매를_등록한다()
- `@RequestPart`를 사용했기 때문에 `CreateAuctionRequest` 또한 `MockMultipartFile`로 생성했으나 타입 자체는 `application/json`임을 확인해주시면 좋을 것 같습니다.
- closed #176

경매 등록 api 변경

---

android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionViewModel.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/model/request/CategoryRequest.kt
android/data/src/main/java/com/ddangddangddang/data/model/request/DirectRegionRequest.kt
android/data/src/main/java/com/ddangddangddang/data/model/request/RegisterAuctionRequest.kt
android/data/src/main/java/com/ddangddangddang/data/model/response/AuctionPreviewsResponse.kt
android/data/src/main/java/com/ddangddangddang/data/model/response/RegisterAuctionResponse.kt
android/data/src/main/java/com/ddangddangddang/data/remote/Service.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt
android/data/src/test/java/com/ddangddangddang/data/Fixtures.kt

경매 등록 시 갤러리 이미지를 서버로 전송할 수 있는 기능을 구현했습니다.
service를 보시면 images 파트와 json body 파트 둘로 나눠서 서버로 전송하고 있고 api 명세도 이에 따라 수정된 상태입니다!
1. 버전 호환성 문제
현재 API 33에서는 잘 동작하는데 이전 버전에서는 잘 동작하지 않는 것 같습니다.
API 30에서는 절대 경로를 가져올 때 cursor의 column 정보를 읽어오는 곳에서 정보를 읽어오지 못하는 문제가 있고,
API 28에서는 절대 경로가 storage로 시작하는데 이 경로의 경우 사용자에게 권한을 얻어와야 하는데 아직 권한을 물어보는 코드는 작성하지 않은 상태입니다.
2. 파일 업로드 시 용량 제한 문제
서버에서 전체 파일이 110MB를 넘지 않도록 설정해 두었는데 현재는 이미지를 압축하는 코드를 작성하지 않아서 이미지를 업로드하는데 문제가 존재합니다.
추후에 이미지를 압축하여 서버로 전송하는 코드를 추가할 예정입니다!
- closed: #175

경매 등록 시 갤러리에 있는 이미지를 서버로 전송하는 기능 구현

---

backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java
backend/ddang/src/main/java/com/ddang/ddang/bid/application/dto/CreateBidDto.java
backend/ddang/src/main/java/com/ddang/ddang/bid/application/dto/LoginUserDto.java
backend/ddang/src/main/java/com/ddang/ddang/bid/application/dto/ReadBidDto.java
backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/BidController.java
backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/dto/LoginUserRequest.java
backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/dto/request/CreateBidRequest.java
backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/dto/request/LoginUserRequest.java
backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/dto/response/ReadBidResponse.java
backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/dto/response/ReadBidsResponse.java
backend/ddang/src/main/java/com/ddang/ddang/bid/presentation/resolver/LoginUserArgumentResolver.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/dto/CreateMessageDto.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/exception/ChatRoomNotFoundException.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/exception/UserNotFoundException.java
backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/ChatRoomController.java
backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/CreateMessageRequest.java
backend/ddang/src/main/java/com/ddang/ddang/chat/presentation/dto/CreateMessageResponse.java
backend/ddang/src/main/java/com/ddang/ddang/configuration/ImageConfiguration.java
backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java
backend/ddang/src/test/java/com/ddang/ddang/bid/application/BidServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/bid/infrastructure/persistence/JpaBidRepositoryTest.java
backend/ddang/src/test/java/com/ddang/ddang/bid/presentation/BidControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java

채팅 전송 API 추가
- `userNotFoundException` 생성
- 메시지 전송 시 메시지 수신자와 발신자 id를 함께 전달받습니다. 잘못된 user id가 전달된 경우 예외를 발생시키게 하기 위해 `UserNotFound`를 추가해두었습니다.
- POST `/chattings/{chatRoomId}/messages`
- 채팅방 아이디를 request DTO에 포함시켜 전달받는 형태로 구현했다가 구현 예정인 채팅 메시지 조회 API 명세와 동일하게 path variable로 전달받도록 구현했습니다.
- closed #151

채팅 전송 API 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/CreateAuctionDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadAuctionDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/application/exception/UserNotAuthorizationException.java
backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
backend/ddang/src/main/java/com/ddang/ddang/configuration/InitializationAuctionConfiguration.java
backend/ddang/src/main/resources/db/migration/V3__alter_auction_tables.sql
backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/domain/AuctionTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImplTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/application/MessageServiceTest.java

- 경매 엔티티에 판매자 필드 추가
- DTO 일부 수정
- 테스트 일부 수정
- flyway V3 스크립트 작성
- AuctionApplication 일부 수정
- sellter 주입 로직 추가
- category 초기화 방식 변경 (생성자 초기화 -> 연관관계 세팅 메서드를 활용한 초기화)
- 경매 삭제 시 판매자인지 검증하는 로직 추가
AuctionController.create에서 고정된 회원 1번(판매자)를 입력하도록 한 상태입니다
추후 로그인 기능이 추가되면 컨트롤러나 CreateAuctionDto등이 전반적으로 변경될 예정입니다
추가로 이전에 변경 사항이 너무 많았던 것은 제가 이상한 코드를 수정하고 있었기 때문이었습니다
처음부터 하니 비교적 금방 끝나네요 
- closed #185

경매 엔티티에 판매자 필드 추가

---

android/app/src/main/java/com/ddangddangddang/android/feature/common/ViewModelFactory.kt
android/app/src/main/java/com/ddangddangddang/android/feature/login/LoginActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/login/LoginViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/global/DdangDdangDdang.kt
android/data/build.gradle
android/data/src/main/java/com/ddangddangddang/data/datasource/AuthLocalDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/AuthRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/local/AuthSharedPreference.kt
android/data/src/main/java/com/ddangddangddang/data/model/request/KakaoLoginRequest.kt
android/data/src/main/java/com/ddangddangddang/data/model/response/TokenResponse.kt
android/data/src/main/java/com/ddangddangddang/data/remote/Service.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepositoryImpl.kt
android/data/src/main/java/com/ddangddangddang/data/repository/RegionRepositoryImpl.kt

카카오로부터 받아온 토큰 정보를 서버에 전송하여 서버 자체 토큰을 받아오는 기능을 구현하였습니다.
서버로부터 받아온 자체 토큰을 EncryptedSharedPreferences에 암호화된 상태로 저장하고 decrypt하여 가져올 수 있도록 하였습니다.
AuthSharedPreferences는 토큰만을 관리합니다.
AuthSharedPreferences는 앱 전체에서 한 번만 생성하여 AuthRepository 생성 시 생성자로 넘겨주도록 하였습니다.
AuthRepository를 통해서만 토큰 정보를 수정하고 가져올 수 있도록 할 예정입니다.
AuthSharedPreferences 생성을 위해서는 context가 필요한데 앱 전체에서 하나의 인스턴스만 생성하고 싶기 때문에 application class에서 AuthSharedPreferences와 AuthRepository를 생성하고 있습니다.
- closed : #230

카카오 소셜로그인 서버 연동

---

backend/ddang/src/main/java/com/ddang/ddang/configuration/initialization/InitializationUserConfiguration.java
backend/ddang/src/main/resources/application-local.yml
backend/ddang/src/main/resources/db/migration/V5__alter_user_tables.sql
backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/configuration/DatabaseCleanListener.java

flyway version 5 script 누락된 컬럼 변경 사항 추가
또 빼먹었습니다..죄송합니다..

flyway version 5 script 누락된 컬럼 변경 사항 추가

---

android/app/build.gradle
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeViewModel.kt
android/app/src/main/res/layout/fragment_home.xml
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionLocalDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt

경매 목록을 새로고침하는 기능을 추가했습니다.
- 경매 목록을 추가로 불러오는 함수와 경매 목록을 새로고침하는 코드는 약간 차이가 있어서 함수를 분리하게 되었습니다!
분리하면서 함수명이 애매해져서 (reget은 아닌 것 같아서^-^) `reload`와 `reset`이라는 이름으로 지어봤는데 괜찮은지 확인 부탁드려요!
- 경매 목록이 무한스크롤이다 보니 눈으로 새로고침이 확인이 어려워 auctions 데이터를 observe하는 부분에서 로그를 찍어 경매 사이즈를 확인해본 결과, 잘 동작하는 것을 확인할 수 있었습니다! 동일한 방법으로 확인 부탁드려요! 
- 새로고침과 무한스크롤 서버 통신이 동시에 이루어지면 경매 목록이라는 같은 데이터를 수정하기 때문에 문제가 발생할 수 있다고 생각하여 기존의 `loadingAuctionInProgress` 프로퍼티를 활용하여 lock을 걸어 한 번에 하나의 통신만 주고받을 수 있도록 하였습니다. (두 기능이 같은 api 통신을 하고 있기도 합니다)
- Close : #263

경매 목록 새로고침 기능 추가

---

android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionActivity.kt
android/app/src/main/java/com/ddangddangddang/android/util/view/DialogFactory.kt
android/app/src/main/res/values/strings.xml
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionLocalDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt

삭제된 경매 상세 조회 시 로컬에 저장된 경매 목록에서 삭제 후 사용자에게 다이얼로그를 보여줘서 존재하지 않는 경매임을 알려줍니다.
사용자가 확인하면 경매 목록으로 돌아옵니다.
- 사용자가 다이얼로그를 확인한 후 페이지를 나가도록 하기 위해서 `cancelable`을 `false`로 설정하여 다이얼로그를 취소할 수 없도록 하였습니다.
- dialog negative 버튼이 필요 없다고 판단하여 아예 넣지 않도록 하기 위해서 util에 있는 DialogFactory 코드를 수정하였습니다.
- 경매가 이미 삭제되어 로컬에서 데이터를 제거해야하는 경우는 `remove`, 경매를 서버에서 삭제하려는 경우는 `delete`로 나누면 어떨까 생각했고, 그래서 함수명을 `remove`로 지었습니다.
- Closed: #266

삭제된 경매 상세 조회 시 데이터를 삭제하고 경매 목록으로 돌아오는 기능 추가

---

android/app/src/main/java/com/ddangddangddang/android/feature/splash/SplashViewModel.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionLocalDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/AuthRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/model/response/ValidateTokenResponse.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionCall.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionCallAdapter.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuthService.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepositoryImpl.kt

자동로그인 기능 서버 연동
- response body가 없을 때(`null`일 때) let 뒤의 함수 블록이 실행되지 않던 문제를 해결
- response body가 없더라도 응답타입이 Unit이면 Success를 반환하도록 수정
- #278

자동로그인 기능 서버 연동

---

backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationUserService.java
backend/ddang/src/main/java/com/ddang/ddang/authentication/configuration/AuthenticationInterceptor.java
backend/ddang/src/main/java/com/ddang/ddang/user/application/UserService.java
backend/ddang/src/main/java/com/ddang/ddang/user/domain/User.java
backend/ddang/src/main/java/com/ddang/ddang/user/infrastructure/persistence/JpaUserRepository.java
backend/ddang/src/main/java/com/ddang/ddang/user/presentation/UserController.java
backend/ddang/src/main/resources/db/migration/V9__alter_user_tables.sql
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationUserServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/bid/presentation/BidControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/user/application/UserServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/user/domain/UserTest.java
backend/ddang/src/test/java/com/ddang/ddang/user/infrastructure/persistence/JpaUserRepositoryTest.java
backend/ddang/src/test/java/com/ddang/ddang/user/presentation/UserControllerTest.java

회원 탈퇴 api 추가
- 매우 간단한 코드라서 딱히..?
- 이후에 회원 탈퇴한 경우 로그인할 수 없는 로직을 추가할 예정입니다 
- closed #282

회원 탈퇴 api 추가

---

backend/ddang/script/prod-deploy-script.sh
backend/ddang/script/prod-pipeline.jenkinsfile
backend/ddang/src/main/resources/db/migration/V5__alter_user_tables.sql

운영 서버 관련 script 변경
- 운영 서버가 잘못된 설정으로 인해 현재 동작하지 않는 상황입니다 (502 발생)
- 운영 서버 jenkins pipeline에서 develop-be로 checkout 하는 것을 develop으로 변경했습니다
- 사실상 현재까지는 develop-be 브랜치가 개발 서버와 운영 서버 모두에 배포가 되고 있던 상황이었습니다
- 배포 스크립트는 주석만 잘못되어 있어서 이것만 수정했습니다
- flyway
- 운영서버는 V4까지 적용된 상태인데 V5를 적용하면서 script의 문제로 인해 실행에 실패한 상황입니다
- users에 없던 created_time, last_modified_time을 추가하는 내용인데 기존에 레코드가 있는 상태에서 컬럼을 추가하면 값이 null이 되는데 not null로 설정해서 이러한 문제가 발생했습니다 
- 개발 서버에서는 다른 더 큰 부분(까먹음)에 문제가 있었는데 그거 해결하다가 얼떨결에 V5도 묻힌 채로 해결이 된 것 같습니다 
- null을 허용한 상태로 created_time / last_modified_time 컬럼 추가 -> null인 컬럼에 now()를 통해 현재 시간으로 값 초기화 -> not null 제약조건 추가의 단계로 변경해주었습니다 
- closed #301

운영 서버 관련 script 변경

---

android/data/src/main/java/com/ddangddangddang/data/remote/AuctionRetrofit.kt

토큰 자동 갱신 로직에서 첫 번째 응답 안 닫아서 발생하던 버그 수정
없음
- #327

토큰 자동 갱신 로직에서 첫 번째 응답 안 닫아서 발생하던 버그 수정

---

backend/ddang/src/docs/asciidoc/docs.adoc
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
backend/ddang/src/main/resources/static/docs/docs.html
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java

- 경매 목록 조회 시 인가 기능 추가
- 안드로이드에게 문의한 결과 인증/인가(로그인 같은)를 제외한 서비스의 모든 api는 인가가 필수가 되었습니다
- 앱도 키자마자 카카오톡 로그인을 해야 하더라고요..
- AuctionController.readAllByLastAuctionId()에서 인가를 위해 `@AuthenticateUser AuthenticationUserInfo ignored`를 인자로 받습니다
- 그런데 인가를 받고 난 정보는 현재 사용되지 않아서 ignored라는 변수명을 붙여주었습니다
- 나중에 특정 경매 글을 감춘다거나 신고한 경매 글을 보이지 않게 한다거나 하는 식으로 확장할 예정이라고 합니다
- closed #323

경매 목록 조회 시 인가 기능 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java

- 경매 목록 조회 쿼리 변경
- 끝까지 미뤄버릴까 두려워서 변경했습니다
- 정렬 및 필터링 기능 적용 전에 하기는 해야 했습니다..
- 변경된 메서드가 단 하나라서 그쪽만 보시면 될 것 같습니다 
- 자세한 내용은 [discussion](https://github.com/woowacourse-teams/2023-3-ddang/discussions/337)을 참고해주시면 될 것 같습니다 
- closed #336

경매 목록 조회 쿼리 변경

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/AuctionService.java
backend/ddang/src/main/java/com/ddang/ddang/auction/configuration/AuctionSearchConditionArgumentResolver.java
backend/ddang/src/main/java/com/ddang/ddang/auction/configuration/exception/InvalidSearchConditionException.java
backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepository.java
backend/ddang/src/main/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImpl.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/AuctionController.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/request/ReadAuctionSearchCondition.java
backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/request/SearchCondition.java
backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java
backend/ddang/src/test/java/com/ddang/ddang/auction/application/AuctionServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/InitializeCommonAuctionData.java
backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/QuerydslAuctionRepositoryImplTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/infrastructure/persistence/SearchTitleQueryTest.java
backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java

경매 목록 검색 시 제목 기반의 검색 기능 추가
- [08.31 - 09.01 백엔드 레벨 4 계획](https://www.notion.so/08-31-09-01-93b7ab36e362461a824359b5d7677742) 기준 경매 검색 기능이 `제목`에 한정되어 있어 일단 제목만 가장 간단한 방식으로 구현했습니다
- 그래서 딱히 주의 깊은 코드는 없고 쿼리 개선 시 리펙토링 할 예정입니다 
- closed #349

경매 목록 검색 시 제목 기반의 검색 기능 추가

---

backend/ddang/src/main/java/com/ddang/ddang/chat/application/MessageService.java
backend/ddang/src/main/java/com/ddang/ddang/notification/application/FcmNotificationService.java

알림 전송 실패 시 로그 추가

---

android/app/src/main/java/com/ddangddangddang/android/feature/common/ErrorType.kt
android/app/src/main/java/com/ddangddangddang/android/feature/login/LoginActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/login/LoginViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/notification/DdangDdangDdangFirebaseMessagingService.kt
android/app/src/main/res/values/strings.xml
android/data/build.gradle
android/data/src/main/java/com/ddangddangddang/data/datasource/AuthRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/datasource/UserRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/model/request/KakaoLoginRequest.kt
android/data/src/main/java/com/ddangddangddang/data/model/request/UpdateDeviceTokenRequest.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionCall.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionService.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepositoryImpl.kt
android/data/src/main/java/com/ddangddangddang/data/repository/UserRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/UserRepositoryImpl.kt
android/data/src/test/java/com/ddangddangddang/data/AuctionRepositoryImplTest.kt
android/data/src/test/java/com/ddangddangddang/data/Fixtures.kt
android/data/src/test/java/com/ddangddangddang/data/study/coroutine/CoroutineTest.kt

- 카카오 로그인 시 디바이스 토큰도 함께 전송하도록 api 수정
- 디바이스 토큰이 새로 발급되면 서버로 전송하는 기능 추가
- 카카오 로그인 시 fcm으로부터 디바이스 토큰을 가져와야 하는데 그러기 위해서는 리스너를 추가해주어야 하고 해당 리스너에서 콜백이 호출되면 디바이스 토큰을 확인하여 서버로 전송 가능합니다.
- 콜백을 기다려야 하기 때문에 콜백이 올때까지 코루틴을 suspend하고 콜백이 오면 resume하도록 해야 했습니다.
- 그래서 드로이드 나이츠 때 배운 [suspendCancellableCoroutine](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/suspend-cancellable-coroutine.html)을 이용하여 구현하게 되었습니다!
- suspendCancellableCoroutine 함수를 실행하면 사용자가 resume하기 전까지 코루틴을 멈출 수 있습니다. 그래서 suspendCancellableCoroutine 내부에 fcm으로부터 디바이스 토큰을 가져오는 콜백을 정의하고 콜백이 호출되면 resume하도록 하였습니다.
- 처음 사용하는 함수이기에 suspendCancellableCoroutine이 원하는대로 잘 동작하는지 테스트도 진행했습니다.
- fcm으로부터 새로운 디바이스 토큰이 발급되면 userRepository를 통해 서버로 디바이스 토큰을 전송하였습니다.
- AuctionRetrofit에 정의된 Interceptor에서 자체적으로 토큰을 검증하기 …

서버로 디바이스 토큰을 전송하는 기능 추가

---

backend/ddang/src/main/java/com/ddang/ddang/image/application/ImageService.java
backend/ddang/src/test/java/com/ddang/ddang/image/application/ProfileImageServiceTest.java

경매 이미지 url 처리에 방법 변경

---

android/app/src/main/java/com/ddangddangddang/android/feature/home/AuctionAdapter.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/AuctionSpaceItemDecoration.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeViewModel.kt
android/app/src/main/res/layout/fragment_home.xml
android/app/src/main/res/values/strings.xml
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/model/SortType.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionService.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt

바뀐 서버 API에 맞게 Repository와 ViewModel을 수정하고, 정렬을 연동했습니다.
SortType이라는 Enum class를 생성했습니다. 현재 API 명세에서는 sortType을 String으로 받고 있는데, 이를 개발자가 수동으로 일일히 입력해야한다면 오타의 발생 가능성이 매우 크고 sortType의 이름이 바뀌었을 때 sortType을 사용하는 모든 코드를 수정해주어야하기 때문입니다.
```kotlin
enum class SortType(name: String) {
NEW("new"), AUCTIONEER("auctioneer"), CLOSING_TIME("closing_time"), RELIABILITY("reliability")
}
```
데이터소스에서는 다음과 같이 사용합니다.
```kotlin
suspend fun getAuctionPreviews(
page: Int,
size: Int?,
sortType: SortType?,
title: String?,
): ApiResponse<AuctionPreviewsResponse> = service.fetchAuctionPreviews(page, size, sortType?.name, title)
```
정렬의 경우 ViewModel에 sortType을 보관하는 변수를 생성했습니다.
이를 통해, 정렬을 바꾼 후 reload를 하더라도 설정한 정렬대로 reload 될 수 있게합니다.
```kotlin
val response = repository.getAuctionPreviews(page = _page, size = …
```

홈 전체 경매 목록 조회 바뀐 API 맞게 수정 및 정렬 연동

---

backend/ddang/src/main/java/com/ddang/ddang/configuration/fcm/LocalFcmConfiguration.java
backend/ddang/src/main/java/com/ddang/ddang/configuration/fcm/ProdFcmConfiguration.java

프로덕션 환경의 FCM 설정과 로컬 환경의 FCM 분리
프로덕션만 신경쓰다보니 로컬에서 실행이 안되는 이슈가 발생했습니다 
그래서 일단 LocalFcmConfiguration과 ProdFcmConfiguration로 분리했는데 LocalFcmConfiguration와 테스트용 MockFcmConfiguration의 코드는 동일합니다
분리한 이유는 LocalFcmConfiguration과 MockFcmConfiguration의 용도와 라이프 사이클이 다르다고 생각했기 때문입니다 
일단 프로덕션 영역에 테스트 코드가 존재하면 안된다고 생각하는 편이므로 실제 동일한 코드를 사용하더라도 의미가 다르다면 분리를 해야 한다고 생각하며 
로컬의 경우 테스트를 위해 로컬과 프로덕션의 FCM을 분리하면서 로컬에서 성능 테스트용과 같은 FCM을 사용할 일이 있다고 생각했기 때문입니다 
- closed #386

프로덕션 환경의 FCM 설정과 로컬 환경의 FCM 분리

---

android/app/src/main/java/com/ddangddangddang/android/feature/common/ViewModelFactory.kt
android/app/src/main/java/com/ddangddangddang/android/feature/search/SearchFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/search/SearchViewModel.kt
android/app/src/main/res/layout/fragment_search.xml
android/app/src/main/res/values/strings.xml
android/data/src/main/java/com/ddangddangddang/data/datasource/AuctionRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionService.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuctionRepositoryImpl.kt

검색 기능 서버 연동을 진행했습니다. HomeFragment와 내용은 유사합니다.
1. ViewModel에서 auctions를 라이브데이터로 만들었고, Fragment에서 이 auctions를 옵저빙하고 있습니다.
2. 그 외에 이벤트는 EditText의 값을 검사하여 Length가 2~20 범위가 아니거나, 통신 시 에러 메시지가 던져졌을 때 ~스낵바를 띄우는 용도로 사용하고 있습니다.~
스낵바를 보여주려니 키보드를 내려줘야하는데, 그럼 사용자는 다시 검색창을 눌러야하므로 누를게 많아서 번거롭다고 판단했습니다. 따라서 스낵바에서 토스트로 변경했습니다.
3. SearchStatus를 추가하여 현재 상태가 검색 전인지, 검색 후 데이터가 없는 상태인지, 검색 후 데이터가 있는 상태인지에 따라 적절한 뷰가 띄워지도록 visibility를 설정했습니다.
4. 원래 있던 getAuctionPreviews가 DataSource 내부 LiveData와 연관이 되어있어 검색에서는 사용할 수 없었습니다. 따라서 오버로딩을 통해 인자 수를 다르게 하여, local에 저장하지 않고 오직 list 결과값을 리턴하는 함수를 만들었습니다.
함수명을 다르게해서 구분하면 좋을 것 같긴한데... 이에 동의하신다면 좋은 네이밍 추천 받습니다!
- closed: #362

검색 기능 서버 연동

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/ddangddangddang/android/feature/common/ViewModelFactory.kt
android/app/src/main/java/com/ddangddangddang/android/feature/myAuction/MyAuctionActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/myAuction/MyAuctionViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageFragment.kt
android/app/src/main/res/layout/activity_my_auction.xml
android/app/src/main/res/layout/activity_profile_change.xml
android/app/src/main/res/values/strings.xml
android/data/src/main/java/com/ddangddangddang/data/datasource/UserRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuctionService.kt
android/data/src/main/java/com/ddangddangddang/data/repository/UserRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/UserRepositoryImpl.kt

나의 경매 목록을 볼 수 있는 기능을 추가했습니다.
만약 응답 성공시, 요청했던 페이지가 1이라면, 이전 정보는 빼고 새로 리스트를 설정했습니다.
상품을 성공적으로 불러왔는데, 상품이 1개도 없을 경우 텍스트를 화면에 보여주기 위해 isLast를 라이브데이터로 했습니다.
- 내 경매 목록에서 상세 상품으로 들어가서 상품을 삭제하고 다시 돌아왔을때, 목록에서 제거되지 않습니다. 일단 기본적으로 서버에서 지금 내 경매 목록에 대해서는 삭제된 상품도 같이 보내주고 있습니다.
만약 서버에서 정책을 바꿔서, 삭제한 상품도 나의 경매 목록에서 보여주지 않도록 된다면, 상세 페이지에서 추가적인 작업이 필요할 것 같습니다. (삭제한 상품의 id정보를 돌려주지 않기 때문에, 만약 필요하다면, 상세 페이지에서 삭제시 상품의 정보를 종료 결과로 보내줘야 할 수도 있을 것 같습니다. 지금 아마 검색쪽에서도 같은 문제가 있을 것 같네요)
- close: #395

나의 경매 목록 기능

---

android/app/src/main/java/com/ddangddangddang/android/feature/main/MainActivity.kt
android/app/src/main/java/com/ddangddangddang/android/notification/DdangDdangDdangFirebaseMessagingService.kt
android/app/src/main/res/values/strings.xml

안드로이드 12이하 버전 알림 권한 및 알림 수신 대응
현재 코드에서는 안드로이드 12 이하일 때 만약 알림 권한이 없다면 권한 설정 다이얼로그를 띄우는데 안드로이드 12 이하의 경우 알림 권한 초기값이 true라고 합나디.
그래서 처음 앱을 시작하는 사용자에게 알림 권한 설정 다이얼로그를 띄우기 위해서는 내부에서 첫 실행 여부를 확인할 수 있는 값을 관리해야 합니다!
땅땅땅에서는 첫 실행시에 권한 설정 다이얼로그를 띄울지 아니면 사용자가 권한을 취소한 경우에만 띄울지 논의가 필요합니다!
- Close: #389

안드로이드 12이하 버전 알림 권한 및 알림 수신 대응

---

backend/ddang/src/main/java/com/ddang/ddang/authentication/application/AuthenticationService.java
backend/ddang/src/main/java/com/ddang/ddang/device/infrastructure/persistence/JpaDeviceTokenRepository.java
backend/ddang/src/main/java/com/ddang/ddang/report/application/AuctionReportService.java
backend/ddang/src/main/java/com/ddang/ddang/report/application/ChatRoomReportService.java
backend/ddang/src/main/java/com/ddang/ddang/report/infrastructure/persistence/JpaAuctionReportRepository.java
backend/ddang/src/main/java/com/ddang/ddang/report/infrastructure/persistence/JpaChatRoomReportRepository.java
backend/ddang/src/main/resources/static/docs/docs.html
backend/ddang/src/test/java/com/ddang/ddang/authentication/application/AuthenticationServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaAuctionReportRepositoryTest.java
backend/ddang/src/test/java/com/ddang/ddang/report/infrastructure/persistence/JpaChatRoomReportRepositoryTest.java

report 정렬 추가 및 탈퇴 시 디바이스 토큰 제거
- closed #427

report 정렬 추가 및 탈퇴 시 디바이스 토큰 제거

---

android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageRoomActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageRoomViewModel.kt
android/app/src/main/res/layout/activity_message_room.xml
android/app/src/main/res/layout/item_my_message.xml
android/app/src/main/res/values/strings.xml

-  쪽지 전송 버튼 활성화 유무 기능 추가
-  메시지 전송 시간 양쪽 사이드 글자 잘려보이던 현상 수정
- 쪽지방 페이지에서 통신 실패 시, ErrorType 적용
내용이 작아서 없는 것 같습니다. 
굳이 꼽자면, 메시지 룸에서 서버 통신 실패의 종류를 세 가지로 sealedclass 로 묶었습니다.
- close: #422

쪽지방 페이지 전송 버튼 활성화 유무 설정 및 글자 기울어져서 잘리는 현상 수정

---

android/app/src/main/java/com/ddangddangddang/android/feature/profile/ProfileChangeActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/profile/ProfileChangeViewModel.kt
android/app/src/main/res/drawable/ic_camera_20_18.xml
android/app/src/main/res/layout/activity_profile_change.xml
android/app/src/main/res/layout/view_profile.xml
android/app/src/main/res/values/strings.xml

회원 정보 페이지에서 프로필 이미지 scaleType 수정 및 회원 수정 정보 요청 시 응답 실패 로직 추가
view_profile.xml 파일에서 실제 변경점은 scaleType = "centerCrop" 밖에 없습니다. 나머지는 코드 정렬하다가 수정 된 것입니다.
- close: #424

회원 정보 페이지에서 프로필 이미지 scaleType 수정 및 회원 수정 정보 요청 시 응답 실패 로직 추가

---

android/app/build.gradle
android/app/src/main/java/com/ddangddangddang/android/feature/splash/SplashActivity.kt
android/app/src/main/res/values/strings.xml

앱 업데이트 매니저 로직 추가
첫 번째 빨간 박스의 조건문 의미는, 앱을 업데이트 할 상위 버전이 플레이스토어에 존재하고, 즉시 업데이트할 수 있는 경우(만약 다른 앱이 백그라운드에서 업데이트 중이면 즉시 못하는 상황이라고 함)에 startUpdateFlowForResult 를 실행해서 업데이트를 진행 페이지로 이동합니다.
만약 업데이트 페이지에서 뒤로가기를 누르면, 다시 스플래시로 오게 되는데, 만약 앱 업데이트 진행중이였다면, 다시 앱 업데이트 페이지로 이동시킵니다.
업데이트가 완료되면, 토큰 유효성 검사해서 자동 로그인 시도를 합니다.
- close: #435

인앱 자동 업데이트 기능 추가

---

backend/ddang/src/main/resources/db/migration/V14__alter_chat_room_report_tables.sql

flyway 문제 발생 해결
14버전에서는 fk에 대한 제약조건을 삭제하지 않은 상태로 fk를 제거하고 있습니다.
이 과정에서 문제가 생겨 서버가 다운되었습니다.
이를 바로 감지하지 못한 이유는 어제 14버전이 적용된 후 제대로 적용되었는 지 확인 했지만, 문제는 발생하지 않았고 오히려 해당 스크립트를 통해 원한 결과를 확인까지 마친 상태였습니다.
그런데 갑작스럽게 오늘 문제가 발생해 뒤늦게 처리하게 되었습니다.

flyway 문제 발생 해결

---

backend/ddang/src/test/java/com/ddang/ddang/auction/presentation/AuctionControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/authentication/presentation/AuthenticationControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/bid/presentation/BidControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/category/presentation/CategoryControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/presentation/ChatRoomControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/configuration/CommonControllerSliceTest.java
backend/ddang/src/test/java/com/ddang/ddang/device/presentation/DeviceTokenControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/image/presentation/ProfileImageControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/region/presentation/RegionControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/report/presentation/ReportControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/user/presentation/UserAuctionControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/user/presentation/UserControllerTest.java

- 컨트롤러 슬라이스 테스트 설정 공통화
- 각 컨트롤러 슬라이스 테스트마다 별도의 ApplicationContext를 사용하던 것을 하나의 ApplicationContext를 재활용하도록 변경했습니다
- 로컬에서 확인했을 때에는 이전 21초 걸리던 테스트가 지금은 17초로 감소했습니다 
- 깃허브 액션에서 캐싱되지 않은 작업 처리할 때 jacoco 테스트 과정이 2분 44초에서 2분 21초에서 감소했습니다 
- CommonControllerSliceTest
- 설정 다 몰아넣은게 끝이기는 합니다 
- closed #239

컨트롤러 슬라이스 테스트 설정 공통화

---

android/app/src/main/java/com/ddangddangddang/android/notification/DdangDdangDdangFirebaseMessagingService.kt
android/app/src/main/java/com/ddangddangddang/android/notification/NotificationType.kt

알림 type에 따라 채팅방 또는 경매 상세 페이지 pending intent를 가진 알림을 생성하도록 하였습니다.
이전 채팅방 알림 수신 기능과 거의 동일합니다.
`NotificationType`이 없는 경우 예외를 발생시켜 디버깅이 쉽도록 하려고 하였으나 추후에 논리 오류에 대한 로깅 처리를 추가하기로 팀원들과 합의하여 현재는 `NotificationType`이 없는 경우 null을 반환하고 알림 기능이 동작하지 않도록 처리했습니다.
- close : #437

경매 알림 수신 기능 추가

---

backend/ddang/src/main/java/com/ddang/ddang/auction/presentation/dto/request/CreateAuctionRequest.java
backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java

예외 처리 방식 및 메시지 수정

---

backend/ddang/src/test/java/com/ddang/ddang/device/application/DeviceTokenServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/device/application/fixture/DeviceTokenServiceFixture.java
backend/ddang/src/test/java/com/ddang/ddang/device/domain/DeviceTokenTest.java
backend/ddang/src/test/java/com/ddang/ddang/device/domain/fixture/DeviceTokenFixture.java
backend/ddang/src/test/java/com/ddang/ddang/device/infrastructure/persistence/JpaDeviceTokenRepositoryTest.java
backend/ddang/src/test/java/com/ddang/ddang/device/infrastructure/persistence/fixture/JpaDeviceTokenRepositoryFixture.java
backend/ddang/src/test/java/com/ddang/ddang/device/presentation/DeviceTokenControllerTest.java
backend/ddang/src/test/java/com/ddang/ddang/device/presentation/fixture/DeviceTokenControllerFixture.java

디바이스 토큰 관련 테스트 코드 리팩토링
- closed #480

디바이스 토큰 관련 테스트 코드 리팩토링

---

backend/ddang/src/test/java/com/ddang/ddang/chat/application/ChatRoomServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/application/fixture/ChatRoomServiceFixture.java
backend/ddang/src/test/java/com/ddang/ddang/chat/domain/ChatRoomTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/domain/fixture/ChatRoomFixture.java
backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/JpaChatRoomRepositoryTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslChatRoomAndImageRepositoryImplTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslChatRoomAndMessageAndImageRepositoryImplTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/QuerydslChatRoomRepositoryImplTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/fixture/JpaChatRoomRepositoryFixture.java
backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/fixture/QuerydslChatRoomAndImageRepositoryImplFixture.java
backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/fixture/QuerydslChatRoomAndMessageAndImageRepositoryImplFixture.java
backend/ddang/src/test/java/com/ddang/ddang/chat/infrastructure/persistence/fixture/QuerydslChatRoomRepositoryImplFixture.java

채팅방 관련 테스트 코드 리팩토링
- closed #479

채팅방 관련 테스트 코드 리팩토링

---

android/app/src/main/java/com/ddangddangddang/android/feature/home/HomeFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/main/MainActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/main/MainViewModel.kt

홈 화면에서 맨 위로 스크롤하는 기능이 없어서 불편하다고 생각했습니다.
그래서 예전 배달의 민족 앱처럼 홈 화면에서 홈 버튼을 누르면 맨 위로 스크롤하도록 기능을 추가했습니다!
홈 화면에서 홈 버튼을 클릭하면 이벤트를 설정하고 MainActivity에서 이벤트를 옵저빙하게 했습니다.
이벤트가 옵저빙되면 supportFragmentManager로부터 HomeFragment를 가져와서 HomeFragment에 정의된 함수를 호출하게 하였습니다!
해당 함수는 경매 목록 리사이클러뷰의 스크롤을 스무스하게 맨 위로 스크롤합니다!
- close: #522

홈 화면에서 홈 버튼 클릭 시 맨 위로 스크롤하는 기능 추가

---

android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/mypage/MyPageViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/util/view/DialogFactory.kt
android/app/src/main/res/layout/fragment_my_page.xml
android/app/src/main/res/values/strings.xml

탈퇴 시 다이얼로그를 띄우고 탈퇴했을 때 유저 정보가 어떻게 되는지 (바로 삭제 or 몇 일동안은 보류) 유저에게 알려주도록 했습니다! 
화면구성에 대응하지는 않았습니다!
탈퇴 다이얼로그의 경우, 화면구성이 변경되었을 때 유지되어야 할 만큼 중요하지 않다고 생각했어요!
(사실 화면구성 변경되어서 다이얼로그 사라지고 유저가 탈퇴할 마음도 함께 사라진다면 오히려 좋을지도...? 라는 못된 생각도 했습니다 😆)
- close: #517

탈퇴 시 다이얼로그 띄우기

---

android/app/src/main/java/com/ddangddangddang/android/di/Annotations.kt
android/app/src/main/java/com/ddangddangddang/android/di/FormatterModule.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageAdapter.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageRoomActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageRoomViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageViewHolder.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageViewItem.kt
android/app/src/main/java/com/ddangddangddang/android/model/MessageModel.kt
android/app/src/main/java/com/ddangddangddang/android/model/mapper/MessageModelMapper.kt
android/app/src/main/res/layout/item_message_room_created_notify.xml
android/app/src/main/res/layout/item_my_message.xml
android/app/src/main/res/layout/item_partner_message.xml
android/app/src/main/res/values/strings.xml

각 날짜별로 첫번째 메시지의 상단에 날짜가 표시되도록 수정 및 메시지에 텍스트 복사 기능만 추가했습니다.
저번 di미션때 레아가 짜주셨던 방법과 유사하게 하려고 포매터를 어댑터의 생성자에서 받도록 수정했습니다.
기존에는 toViewItem을 호출해서 내 메시지와 상대 메시지타입을 나눴었는데, 그 전에 먼저 합쳐진 상태에서 이번에 뒤에 더 추가하려는 메시지들에 대해서 toViewItems()를 호출하는 방식으로 수정했습니다. 
추가하려는 메시지들 중 가장 앞에 있는(인덱스가 0인) 메시지는 기존의 메시지 중 가장 뒤에 있는 메시지의 LocalDate와 비교합니다. 
아래 보이시는 것처럼, 효율적인 비교를 위해 내 바로 앞에 있는 메시지의 LocalDate하고만 비교하며, map문의 순회 한번이 끝날때마다 sendTime을 previousSendDate에 할당해줘서 다음번 순회에서 중복으로 불필요하게 이전 아이템의 LocalDate구하는 과정을 없앴습니다.
- close: #516

각 날짜별로 첫번째 메시지의 상단에 날짜가 표시되도록 수정

---

backend/ddang/src/main/java/com/ddang/ddang/exception/GlobalExceptionHandler.java
backend/ddang/src/main/resources/application.yml
backend/ddang/src/main/resources/log/console-logging.xml
backend/ddang/src/main/resources/log/file-error-logging.xml
backend/ddang/src/main/resources/log/file-info-request-logging.xml
backend/ddang/src/main/resources/log/file-warn-logging.xml
backend/ddang/src/main/resources/log/slack-error-logging.xml
backend/ddang/src/main/resources/logback-spring.xml

- warn, error 레벨 로그 포맷 변경
- warn, error 레벨 모두 json 형태로 출력하도록 변경했습니다
- MDC를 통해 어떠한 요청에서 예외가 발생했는지 추적할 수 있도록 설정했습니다 
- warn은 예외의 stack trace를 출력하지 않도록 했으며 error만 출력하도록 했습니다 
- GlobalExceptionHandler에서 잘못된 레벨로 로그를 출력하던 내용을 변경했습니다
- 상태코드 500이었으나 warn 레벨이던걸 error로 변경했습니다
- logback-spring.xml에서 profile 별로 xml을 분리했습니다 
- 잘못된 설정값을 수정했습니다
- timestamp 포맷 설정 방식 변경 
- json pretty 설정 삭제(\n이 추가되므로 그라파나에서 확인할 때 매우 지저분해짐) 
- closed #530

warn, error 레벨 로그 포맷 변경

---

backend/ddang/src/main/java/com/ddang/ddang/bid/application/BidService.java

입찰 관련 알림 수신자 변경
이전 입찰자가 아니라 입찰한 사람에게 상위입찰자가 있다고 알림이 오고 있습니다.
마지막 입찰 갱신 전에 이전 입찰자를 가지고오고 나서 마지막 입찰을 갱신해야하는데 그 순서가 바뀌어서 생긴 문제였습니다.
`saveBid()`라는 메서드명이 메서드가 하는 일을 적절히 나타내지 못해 생긴 이슈일 수도 있겠다 싶어서 `saveAndUpdateLastBid()`로 메서드명을 수정했습니다.
- closed #550

입찰 관련 알림 수신자 변경

---

android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageRoomActivity.kt
android/app/src/main/java/com/ddangddangddang/android/notification/ActiveNotificationManager.kt
android/app/src/main/java/com/ddangddangddang/android/notification/DdangDdangDdangFirebaseMessagingService.kt

- 메시지 알림
채팅방 아이디가 같은 알림이 이미 존재하는 경우, InboxStyle의 확장형 알림을 구현하였습니다.
채팅방으로 이동 시, 채팅방과 관련된 활성화 알림을 취소하도록 했습니다.
- 경매 알림
경매방 아이디가 같은 알림이 이미 존재하는 경우, 기존의 알림을 덮어씌우도록 하였습니다.
경매 알림의 경우, 사용자가 경매방으로 이동하여 새로 입찰하지 않는 한 새로운 알림이 오지 않기 때문에 위와 같이 구현했습니다.
경매방으로 이동 시, 경매방과 관련된 활성화 알림을 취소하도록 했습니다. 
```kotlin
internal fun Context.getActiveNotification(tag: String, id: Int): Notification? {
val notificationManager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
return notificationManager.activeNotifications.firstOrNull {
it.tag == tag && it.id == id
}?.notification
}
```
=> 활성화된 알림 중 태그와 아이디가 같은 알림이 있다면 가져오는 코드입니다.
```kotlin
val previousLines =
activeNotification?.extras?.getCharSequenceArray(EXTRA_TEXT_LINES) ?: emptyArray()
```
=> 태그와 아이디가 같은 알림의 InboxStyle에 addLine 함수로 추가된 문자열을 배열로 …

알림 태그와 아이디가 같은 알림 쌓는 기능 및 알림 관련 페이지 이동 시 알림 취소 기능 구현

---

android/app/src/main/java/com/ddangddangddang/android/feature/messageRoom/MessageRoomActivity.kt
android/app/src/main/java/com/ddangddangddang/android/notification/DdangDdangDdangFirebaseMessagingService.kt
android/app/src/main/java/com/ddangddangddang/android/reciever/MessageReceiver.kt

브로드 캐스트 리시버를 활용해서, fcm 수신시 해당 메시지 룸 id를 담은 인텐트와 액션을 담아서 방송을 송신함. 
MessageRoomActivity에서는 동적으로 브로드캐스트리시버를 등록해서 이 액티비티가 있는 동안에만 수신해줌.
아래처럼, 사용하기 쉽게 만들어놔서, 다른 곳에서도 메시지 수신이 필요하면 사용해볼 수 있을 것 같네요. 일단은 MessageRoomActivity에만 적용했습니다. MessageFragment도 받도록 해서 메시지 오면 메시지 방 리스트 갱신하는 것도 좋을 것 같네요
여기서 빨간 박스 친 부분은 나중에 글로꺼 머지되고 수정하면 좋을 것 같습니다. 이번에 글로쪽 pr에서도 많이 바뀐 것 같아서 현재 구조를 괜히 함수 분리로 건들였다가 머지 할때 충돌 날거 같네요
- close: #528

메시지 실시간 동기화 기능 추가

---

backend/ddang/src/main/java/com/ddang/ddang/user/presentation/dto/response/ReadAuctionResponse.java

경매 이미지가 경매 id와 동일한 값으로 전달되는 버그
- ReadAuctionResponse에서 발생한 이슈입니다 
- `ImageUrlCalculator.calculateBy(ImageRelativeUrl.AUCTION, dto.id())`처럼 경매 id를 넣어주고 있어서 발생한 이슈였습니다
- 이 부분만 수정했습니다 
- closed #574

경매 이미지가 경매 id와 동일한 값으로 전달되는 버그 수정

---

android/app/src/main/res/layout/activity_auction_detail.xml

하위 버전에서 상세 페이지의 제목 글자 흐르지 않던 문제 해결을 위해 찾아본 결과, 글자 흐름과 글자 복사 가능 기능을 같이 넣기 위해서는 핸들러를 사용해서 액티비티가 재개되고 잠시후에 동적으로 수정해야 한다는 자료를 발견했습니다. 하지만, 애초에 상세 페이지에서 제목 복사 기능은 혹시 있으면 좋을 것 같아서 넣었던 코드입니다. 굳이 필수도 아닌데 불안정한 것에 대응하는 코드를 넣을 필요는 없을 것 같다고 느껴져서 복사 기능을 제거했습니다.
https://stackoverflow.com/questions/33872104/setting-textisselectable-on-textview-with-marquee-ellipsize-adds-ellipse
없음
- close: #576

하위 버전에서 상세 페이지의 제목 글자 흐르지 않던 문제 해결

---

android/app/src/main/java/com/ddangddangddang/android/feature/main/MainActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/main/MainBindingAdapter.kt
android/app/src/main/java/com/ddangddangddang/android/feature/main/MainViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/util/view/BackKeyHandler.kt
android/app/src/main/res/layout/activity_main.xml
android/app/src/main/res/values/strings.xml

메인 화면에서 뒤로가기 누를때 처리 로직 추가
- 홈이면, 뒤로 가기 두 번 눌러야 종료되는 로직 시작
- 홈이 아니면, 홈으로 이동.
뒤로 가기를 2초안에 다시 눌러야 종료되도록 되어있습니다.
위의 콜백 로직을 보면 알 수 있듯이, 홈 프래그먼트에서 뒤로 두 번을 누르면 종료되도록 되어있습니다.
바텀네비게이션의 selectedId를 바꿔주면, 바텀탭이 이동하고 저희가 등록한 리스너도 호출되어서, 뷰모델이 보관하는 프래그먼트 상태도 바뀌게 됩니다.
- close: #580

메인 화면에서 백키 핸들러 추가

---

android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailActivity.kt
android/app/src/main/res/layout/activity_auction_detail.xml
android/app/src/main/res/layout/item_detail_auction.xml
android/app/src/main/res/values/dimens.xml

경매 상세 페이지에서 이미지 스크롤 좌우 감지 안되던 버그 수정
=> 뷰페이저가 스크롤될 때마다, 중앙에서 나가는 녀석들을 강제로 자신쪽으로 이동시킵니다.  들어오는 녀석들도 강제로 자신쪽으로 이동시킵니다. 즉, 만약 우측 이미지로 이동하고 있는 중이라면, 기존에 중앙보다 우측에 있던 이미지는 원래 있어야할 위치보다 x축으로 -만큼 당겨져오고, 기존에 중앙보다 좌측에 있던 이미지는 원래 있어야 할 위치보다 x축으로 +만큼 가게 되어서, 결국에는 기존의 뷰홀더 간 마진 거리보다 가까워지게 됩니다. 이때, 뷰페이저에서 여러 개의 뷰홀더 요소들을 보여주기 위해서는 뷰페이저에 clipToPadding과 clipChildren 값을 false로 줘야 합니다. 이것에 대한 정보는 제가 말로 하는 것보다 블로그를 참고하는 것이 빠를 것 같아서, 제가 아래에 링크도 남겨놓겠습니다. 해당 내용에 대해서는 내일 다시 말씀 드리겠습니다.
참고로 뷰페이저2는 내부적으로 리사이클러뷰를 갖고 있습니다. clipToPadding을 해줘서 뷰페이저에 대한 패딩이 아니라 뷰페이저 안에 있는 스크롤녀석들에 대해 첫번쨰와 마지막 요소에 대해서 패딩을 주게 됩니다, clipChildren을 사용해서 뷰페이저가 그릴 수 있도록 리사이클러뷰에게 원래 제공하는 영역을 넘어서, 사이드에 있는 페이지들에 대해서 뷰페이저 안에 그려질 수 있게 하는 것입니다.
좀 더 확실한 이해는 아래 블로그 짧으니 확인해주시면 될 것 같습니다.
- clipChildren 설명
https://leveloper.tistory.com/175
- clipToPadding 설명 …

경매 상세 페이지에서 이미지 스크롤 좌우 감지 안되던 버그 수정

---

backend/ddang/src/main/java/com/ddang/ddang/auction/application/dto/ReadChatRoomDto.java
backend/ddang/src/main/java/com/ddang/ddang/auction/domain/Auction.java
backend/ddang/src/main/java/com/ddang/ddang/chat/application/ChatRoomService.java
backend/ddang/src/main/java/com/ddang/ddang/user/domain/User.java
backend/ddang/src/test/java/com/ddang/ddang/chat/application/ChatRoomServiceTest.java
backend/ddang/src/test/java/com/ddang/ddang/chat/application/fixture/ChatRoomServiceFixture.java

경매 상세 조회 시 경매글을 찾을 수 없을 때만 404를 보내도록 수정
없음
- closed #603

경매 상세 조회 시 경매글을 찾을 수 없을 때만 404를 보내도록 수정

---

android/app/src/main/java/com/ddangddangddang/android/feature/message/MessageFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/message/MessageViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/notification/DdangDdangDdangFirebaseMessagingService.kt

메시지 방 목록에 브로드캐스트 리시버 등록 및 해제 로직 추가
사실 아래 코드가 전부 입니다.
우선 저희가 지금 프래그먼트를 사용하고 hide/show를 사용해서 onResume 혹은 onPause는 바텀 네비게이션 탭간 전환으로는 발생하지 않습니다. 
또한, 메시지방에 다녀오거나 홈키를 눌러서 아예 앱을 나갔다가 다시 메시지 프래그먼트로 돌아오는 경우에는 onHiddenChanged가 발생하지 않습니다.
이 모든 문제를 해결하기 위해서 양쪽에 모두 등록과 해제 로직을 설정해줬습니다. 
다만 여기서 문제가 하나 있었는데, 브로드캐스트 리시버 등록 같은 경우는 동일한 리시버를 여러번 등록해도 한 번밖에 수신되지 않고 또 한 객체를 여러번 등록을 시도한다고 해서 예외가 발생하지도 않습니다, 
해제에서 문제가 발생했었는데, 등록된 리시버가 아닌데 해제를 시도하면 예외를 발생하고 터지는 문제가 발생했습니다. 때문에 runChatching으로 해제 로직을 한 번 잡아주고 있습니다.
그렇다면, 해제가 문제가 되는 경우는 언제가 있는지 말씀드려보면, 다음과 같은 상황이 있습니다.
메시지 프래그먼트로 바텀 탭 눌러서 이동(리시버 등록됨) -> 다른 프래그먼트로 탭 눌러서 이동(리시버는 해제됐으나 프래그먼트는 Resumed상태로 hide됨) -> 이 상태에서 홈키를 눌러서 나감 -> Resumed상태였던 메시지 프래그먼트가 onPause 호출 -> 해제하려고 시도하나 등록된게 없어서 예외 발생
-> 추가로 위 사진에서, show될때와 onResume에서 모두 loadMessage()를 호출하고 있어서, 중복 호출은 아닐지 …

메시지 방 목록에 브로드캐스트 리시버 등록 및 해제 로직 추가

---

android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/region/SelectRegionsActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/region/SelectRegionsViewModel.kt

지역을 선택한 후 다시 지역을 선택하더라도 이전에 선택한 지역을 유지하도록 기능을 추가했습니다! 
ParcelableArrayCompat을 정의하면 Parcelable로도 리스트 전달이 가능할 것 같지만 기존에 Serializable을 사용하고 있었기 때문에 이번에도 Serializable 형태로 전송하도록 했습니다! 😉
- close : #629

이전에 선택한 지역 유지 기능 추가

---

android/app/src/main/java/com/ddangddangddang/android/feature/main/MainActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/main/MainViewModel.kt

알림 권한 묻는 이벤트를 SingleLiveEvent로 변경
MainViewModel이 초기화될 때 알림 권한 이벤트 trigger
- 화면 구성이 변경되면 알림 권한을 설정하지 않은 경우, 알림 권한을 다시 묻고 있어서 위와 같이 수정했습니다.
- MainViewModel이 초기화될 때 알림 권한 이벤트를 trigger하게 했는데 이렇게하면 직접적인 의존성은 없지만 뷰모델이 뷰에 의존적이게 되는 걸까요...?
- close: #682

화면 구성 변경이 되더라도 알림 권한을 다시 묻지 않도록 수정

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/ddangddangddang/android/feature/common/ErrorTypeHandler.kt
android/app/src/main/java/com/ddangddangddang/android/feature/detail/DetailFragmentType.kt
android/app/src/main/java/com/ddangddangddang/android/feature/login/LoginActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/login/LoginViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/main/MainActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/onboarding/OnBoardingActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/onboarding/OnBoardingFragmentAdapter.kt
android/app/src/main/java/com/ddangddangddang/android/feature/onboarding/OnBoardingPageType.kt
android/app/src/main/java/com/ddangddangddang/android/feature/onboarding/OnBoardingViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/onboarding/profile/ProfileSettingFragment.kt
android/app/src/main/java/com/ddangddangddang/android/feature/onboarding/profile/ProfileSettingViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/profile/ProfileChangeViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/splash/SplashActivity.kt
android/app/src/main/res/layout/activity_onboarding.xml
android/app/src/main/res/layout/fragment_profile_setting.xml
android/app/src/main/res/values/strings.xml
android/data/src/main/java/com/ddangddangddang/data/datasource/AuthRemoteDataSource.kt
android/data/src/main/java/com/ddangddangddang/data/model/response/LoginByKakaoResponse.kt
android/data/src/main/java/com/ddangddangddang/data/remote/AuthService.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepository.kt
android/data/src/main/java/com/ddangddangddang/data/repository/AuthRepositoryImpl.kt

소셜 로그인할 때 만약 첫 회원가입인 경우, 닉네임 및 프로필 설정페이지를 먼저 보여주기
온보딩 액티비티 및 프로필 세팅 프래그먼트 추가 및 로그인 로직 수정
로그인 api에 대한 응답값을 다음과 같이 변경했습니다.
그에 따라, 로그인 api 결과를 분기처리 하는 로직이 추가됐습니다. 
온보딩 액티비티 주요로직
온보딩 화면에서 뒤로가기는 이전 프래그먼트로 돌아가는 처리로 설정했습니다. 이 액티비티를 나가고 싶다면, 마지막 프래그먼트 페이지에 도달해서 '마치기' 버튼을 클릭하거나, 상단에 있는 건너뛰기 버튼을 눌러야 합니다. 
건너뛰기를 누르는 경우, 다음과 같은 화면이 나옵니다.
우선, 온보딩 액티비티는 회원가입을 한 유저를 위한 페이지입니다. 프로필 설정 외에도 추후에 여러 소개 페이지들이 추가되어야 할 수 있다라고 생각을 해서, 다음과 같이 뷰페이저로 화면을 분할해서 이전과 다음 페이지로 넘길 수 있게 했습니다.
현재는 아래처럼, ProfileSettingFragment 만 있습니다. 때문에 ProfileSettingFragment가 마지막 프래그먼트이므로, '마치기' 버튼을 갖고 있습니다. 만약 이 뒤에 새로운 프래그먼트가 더 보여져야 한다면, > 와 같은 이동 버튼이 필요할 것입니다.
온보딩뷰모델에서는 다음과 같은 함수들을 제공합니다.
여기서, 이전페이지 이동과 다음페이지 이동 메소드는 각 프래그먼트들이 액티비티뷰모델을 통해서 호출할 녀석들입니다. 
온보딩 액티비티의 주요 옵저빙 로직은 다음과 같습니다.
마지막으로, ProfileSettingViewModel은 기존의 …

소셜 로그인할 때 만약 첫 회원가입인 경우, 닉네임 및 프로필 설정페이지를 먼저 보여주기

---

android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailBottomButtonStatus.kt
android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailFormatter.kt
android/app/src/main/java/com/ddangddangddang/android/feature/detail/AuctionDetailViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/model/AuctionDetailModel.kt
android/app/src/main/java/com/ddangddangddang/android/model/mapper/AuctionDetailModelMapper.kt
android/app/src/main/res/layout-land/activity_auction_detail.xml
android/app/src/main/res/layout/activity_auction_detail.xml
android/app/src/main/res/layout/fragment_auction_info.xml
android/app/src/main/res/values/strings.xml
android/data/src/main/java/com/ddangddangddang/data/model/response/AuctionDetailResponse.kt
android/data/src/main/java/com/ddangddangddang/data/model/response/AuctionResponse.kt

경매 상세 페이지 수정
=> 우선, 여기서 파란색 박스는 기존에 있던 로직에서 액션바의 속성을 잘못 선택해서 오차가 발생하고 있던 것입니다. 그 이유는 다음과 같습니다. 요약하자면, 액션바 속성이 두 개가 있는데 그 중 다른걸 사용하고 있어서 수정했습니다.
https://stackoverflow.com/questions/26449195/new-theme-appcompat-actionbar-height
빨간색 박스 로직에 대한 설명)
=> 여기서, getRemainHeight에서 Context.resources.displayMetrics.heightPixels 는 상태바 높이 + 액티비티 높이(이 안에 툴바도 포함)를 반환합니다. 이 메소드는 네비게이션 바의 높이를 안주기 때문에 큰 장점이 있습니다. 네비게이션 바는 모드가 기종마다 혹은 회사마다 여러 가지라서 개발자가 신경쓰기 힘든 부분인데 이를 고려대상에서 제외한 사이즈를 주기 때문에 아주 나이스합니다.
또한, 안드로이드에서 상태바의 높이는 24dp입니다. 
그렇다면, 저희는 다음과 같이 빼면 정말 딱 맞는 뷰페이저의 높이를 구할 수 있습니다.
Context.resources.displayMetrics.heightPixels - 상태바 높이 - 툴바 높이 - 탭레이아웃 높이 - 상세페이지의 하단 입찰 버튼 높이
하지만, 여기서 문제가 있습니다. 
갤럭시의 경우, 펀치홀이 상태바에 있는 세로모드의 경우, Context.resources.displayMetrics.heightPixels 에서 상태바 높이가 이미 빠진 상태로 나오게 된다는 결론을 내리게 …

경매 상세 페이지 수정(마감기한 시간 정보 뷰 수정 및 최고 입찰자 표시)

---

android/app/src/main/java/com/ddangddangddang/android/feature/common/PriceTextWatcher.kt
android/app/src/main/java/com/ddangddangddang/android/feature/detail/bid/AuctionBidDialog.kt
android/app/src/main/java/com/ddangddangddang/android/feature/detail/bid/AuctionBidViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/feature/register/RegisterAuctionActivity.kt
android/app/src/main/res/values/strings.xml

입찰시 커서 유지 기능 추가
- getCursorPosition 함수에서 PriceTextWatcher에서 관리하는 cursorPositionFromEnd 값을 사용하지 않는 이유는 커서를 가져오기 이전에 새로운 입력이 발생하여 값이 변경될 수 있기 때문입니다!
- _**근데 생각해보니 커서를 세팅하기 이전에 새로운 입력이 발생할 수 있을지 의문이 드는데 여러분의 생각은 어떠신가요? 🤔**_
- 쉼표 개수가 필요한 쉼표보다 적은 경우에만 커서를 한 칸 앞으로 이동한 이유는 쉼표가 지워진 경우에만 한 칸 앞으로 이동하기 위해서 입니다!
- trim을 두 번 해준 이유는 사용자가 원 또는 공백을 지운 경우에 입찰 금액이 0으로 초기화되는 것을 막기 위해서 입니다!
- close: #675

입찰시 커서 유지 기능 추가

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/ddangddangddang/android/feature/main/MainActivity.kt
android/app/src/main/java/com/ddangddangddang/android/feature/main/MainBindingAdapter.kt
android/app/src/main/java/com/ddangddangddang/android/feature/main/MainFragmentType.kt
android/app/src/main/java/com/ddangddangddang/android/feature/main/MainViewModel.kt
android/app/src/main/java/com/ddangddangddang/android/notification/type/MessageType.kt
android/app/src/main/java/com/ddangddangddang/android/notification/type/NotificationType.kt

알림을 클릭하면 알림 화면이 부모 화면 위에 쌓여서 알림 화면을 닫으면 부모 화면이 나옵니다.
현재 모든 알림의 부모 화면이 MainActivity여서 MainActivity 위에 알림 화면이 쌓입니다.
단, 유저가 앱을 사용하다가 알림을 누르면 이전 스택은 모두 사라지고 MainActivity와 알림 화면만 스택에 존재합니다.
~또한 부모 화면 지정은 가능하지만 부모 화면의 탭을 지정하는 것은 불가능하여 메시지룸을 나갔을 때 경매 목록이 보입니다 😢~
부모 화면의 탭 지정까지 현재는 가능한 상태입니다! 😉
없음.
- close: #702

알림 화면이 부모 화면 위에 쌓이는 기능 추가

---

backend/ddang/src/docs/asciidoc/docs.adoc
backend/ddang/src/main/java/com/ddang/ddang/chat/domain/Message.java
backend/ddang/src/main/java/com/ddang/ddang/report/domain/AnswerReport.java
backend/ddang/src/main/java/com/ddang/ddang/report/domain/AuctionReport.java
backend/ddang/src/main/java/com/ddang/ddang/report/domain/ChatRoomReport.java
backend/ddang/src/main/resources/static/docs/docs.html
backend/ddang/src/test/java/com/ddang/ddang/bid/presentation/fixture/BidControllerFixture.java

restdocs 문서가 깨지는 문제 해결
- closed #718

restdocs 문서가 깨지는 문제 해결
